<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

/**
 * Şehir sayfaları.
 *
 * Her şehrin metni o pazara özgü yazıldı: Girne'de turizm ve yabancı müşteri,
 * Magosa'da öğrenci nüfusu, Bursa'da bayi ağı… Aynı metnin şehir adı
 * değiştirilmiş kopyaları arama motorlarınca kapı sayfası (doorway page)
 * sayılır ve cezalandırılır.
 *
 * Metinler pazar gözlemi ve hizmet tanımıdır; uydurma referans, müşteri sayısı
 * ya da başarı iddiası içermez.
 */
class LocationSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->locations() as $i => $location) {
            Location::query()->updateOrCreate(
                ['slug' => $location['slug']],
                $location + ['sort_order' => $i + 1, 'is_active' => true],
            );
        }
    }

    private function locations(): array
    {
        return [
            /* ── Kuzey Kıbrıs ───────────────────────────────────────────── */
            [
                'slug' => 'lefkosa',
                'name' => 'Lefkoşa',
                'name_en' => 'Nicosia',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.1856,
                'longitude' => 33.3823,
                'headline' => 'Lefkoşa web tasarım',
                'headline_en' => 'Web design in Nicosia',
                'intro' => 'Başkentte kurumsal beklenti yüksek: banka, sigorta, hukuk, muhasebe ve kamu tedarikçisi firmalar için siteniz ilk referans kontrolüdür.',
                'intro_en' => 'Corporate expectations run high in the capital: for banks, insurers, law and accounting firms and public-sector suppliers, your site is the first reference check.',
                'highlights' => ['Kurumsal ve kamu tedarikçisi firmalar', 'İki dilli (TR + EN) içerik ihtiyacı yüksek', 'Kariyer ve ihale sayfaları', 'Kurumsal kimlikle uyumlu ciddi tasarım'],
                'highlights_en' => ['Corporate and public-sector suppliers', 'High demand for bilingual (TR + EN) content', 'Careers and tender pages', 'Serious design that matches corporate identity'],
                'body' => '<p>Lefkoşa, KKTC\'nin idari ve finansal merkezi. Buradaki müşteri profili diğer şehirlerden belirgin şekilde farklı: karar verici çoğu zaman bir satın alma birimi ya da yönetim kurulu, ve sitenize "bu firma ciddi mi" sorusunun cevabını aramaya geliyor.</p><h2>Başkentte site neye yarıyor</h2><p>Lefkoşa\'da web sitesi genelde doğrudan satış aracı değil, <strong>güven doğrulama aracı</strong>. Bir kurum sizinle çalışmadan önce siteye bakıyor; ekip, referanslar, kurumsal bilgiler ve iletişim netse süreç ilerliyor.</p><h3>Sık ihtiyaç duyulanlar</h3><ul><li>Kurumsal kimlik sayfaları: hakkımızda, ekip, politikalar</li><li>Hizmet detay sayfaları — ihale ve teklif süreçlerinde referans verilecek</li><li>Kariyer bölümü; Lefkoşa\'da nitelikli personel rekabeti yoğun</li><li>İngilizce sürüm: uluslararası kuruluşlar ve elçilik çevresiyle çalışan firmalar için şart</li></ul><h2>Hangi paket uygun</h2><p>Çok sayfalı yapı, blog ve iki dil gerektiği için Lefkoşa\'daki kurumsal firmalar çoğunlukla Kurumsal paketle ilerliyor. Sadece varlık göstermek isteyen küçük ofisler için Basic yeterli oluyor.</p>',
                'body_en' => '<p>Nicosia is the administrative and financial centre of North Cyprus. The customer profile here differs markedly from other cities: the decision maker is often a procurement unit or a board, and they arrive at your site looking for an answer to one question — "is this company serious?"</p><h2>What a site does in the capital</h2><p>In Nicosia a website is usually not a direct sales tool but a <strong>trust verification tool</strong>. An institution checks the site before working with you; if the team, references, corporate details and contact information are clear, the process moves forward.</p><h3>Commonly needed</h3><ul><li>Corporate identity pages: about, team, policies</li><li>Service detail pages — referenced during tender and proposal processes</li><li>A careers section; competition for qualified staff in Nicosia is intense</li><li>An English version: essential for firms working with international organisations</li></ul><h2>Which package fits</h2><p>Because a multi-page structure, a blog and two languages are needed, corporate firms in Nicosia usually go with the Corporate package. For small offices that only need a presence, Basic is enough.</p>',
                'seo_title' => 'Lefkoşa Web Tasarım | Kurumsal Site ve E-Ticaret',
                'seo_title_en' => 'Web Design in Nicosia | Corporate Sites and E-Commerce',
                'seo_description' => 'Lefkoşa\'da kurumsal web sitesi, e-ticaret ve özel yazılım. İki dilli yapı, kariyer ve hizmet detay sayfaları. Fiyatlar açıkça yazılı.',
                'seo_description_en' => 'Corporate websites, e-commerce and custom software in Nicosia. Bilingual structure, careers and service pages. Prices written openly.',
            ],
            [
                'slug' => 'girne',
                'name' => 'Girne',
                'name_en' => 'Kyrenia',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.3364,
                'longitude' => 33.3192,
                'headline' => 'Girne web tasarım',
                'headline_en' => 'Web design in Kyrenia',
                'intro' => 'Girne\'de müşterinizin yarısı sizi Türkçe aramıyor. Otel, restoran, marina ve emlak işlerinde site çok dilli olmak ve rezervasyona götürmek zorunda.',
                'intro_en' => 'In Kyrenia half your customers are not searching in Turkish. For hotels, restaurants, the marina and real estate, a site has to be multilingual and lead to a booking.',
                'highlights' => ['Turizm, konaklama ve restoran ağırlıklı', 'İngilizce şart; Rusça talebi de var', 'Rezervasyon ve müsaitlik akışı', 'Görsel ağırlıklı, mobilde hızlı yapı'],
                'highlights_en' => ['Tourism, hospitality and restaurants', 'English essential; Russian often requested', 'Booking and availability flows', 'Image-heavy but fast on mobile'],
                'body' => '<p>Girne, KKTC\'nin turizm merkezi ve yabancı yerleşik nüfusun en yoğun olduğu şehir. Bu iki şey web sitesi ihtiyacını doğrudan belirliyor.</p><h2>Çok dillilik lüks değil, zorunluluk</h2><p>Girne\'de bir otelin, restoranın ya da emlak ofisinin ziyaretçilerinin önemli kısmı İngilizce arama yapıyor. Türkçe tek dilli bir site, bu trafiğin tamamını rakibe bırakıyor. Bizde her pakette ikinci dil eklenebiliyor; Kurumsal pakette TR + EN zaten dahil.</p><h3>Turizm işletmelerinde sık istenenler</h3><ul><li>Oda / masa müsaitlik ve rezervasyon talebi formu</li><li>Galeri: mekânı gerçekten gösteren, sıkıştırılmış ve hızlı yüklenen fotoğraflar</li><li>Google Business Profile ile uyumlu iletişim ve harita bilgisi</li><li>WhatsApp üzerinden anlık iletişim — sezonda telefondan hızlı</li></ul><h2>Mobil hız burada daha kritik</h2><p>Ziyaretçinin çoğu sokakta, telefonda ve çoğu zaman yavaş bir bağlantıda. Ağır bir galeri sayfası satışı kaybettiriyor. Görselleri modern formatta ve doğru boyutta veriyoruz.</p>',
                'body_en' => '<p>Kyrenia is the tourism centre of North Cyprus and has the densest foreign resident population. Those two facts define the website requirement directly.</p><h2>Multilingual is not a luxury</h2><p>A significant share of visitors to a hotel, restaurant or estate agency in Kyrenia search in English. A Turkish-only site hands all of that traffic to a competitor. A second language can be added to any package; the Corporate package already includes TR + EN.</p><h3>Frequently requested by hospitality businesses</h3><ul><li>Availability and booking request forms</li><li>A gallery that genuinely shows the venue — compressed and fast to load</li><li>Contact and map details consistent with the Google Business Profile</li><li>WhatsApp for instant contact — faster than the phone in season</li></ul><h2>Mobile speed matters more here</h2><p>Most visitors are outdoors, on a phone, often on a slow connection. A heavy gallery page loses the sale. We serve images in modern formats at the right dimensions.</p>',
                'seo_title' => 'Girne Web Tasarım | Otel, Restoran ve Emlak Siteleri',
                'seo_title_en' => 'Web Design in Kyrenia | Hotel, Restaurant and Property Sites',
                'seo_description' => 'Girne\'de çok dilli web sitesi, rezervasyon akışı ve e-ticaret. Turizm ve emlak işletmeleri için mobilde hızlı, İngilizce destekli yapı.',
                'seo_description_en' => 'Multilingual websites, booking flows and e-commerce in Kyrenia. Fast on mobile with English support for tourism and property businesses.',
            ],
            [
                'slug' => 'gazimagusa',
                'name' => 'Gazimağusa',
                'name_en' => 'Famagusta',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.125,
                'longitude' => 33.95,
                'headline' => 'Gazimağusa web tasarım',
                'headline_en' => 'Web design in Famagusta',
                'intro' => 'Öğrenci nüfusu Magosa\'nın ekonomisini şekillendiriyor. Burada müşteri telefonla aramıyor; Instagram\'dan bakıp siteden sipariş veriyor.',
                'intro_en' => 'The student population shapes Famagusta\'s economy. Here customers do not call — they check Instagram and order from the site.',
                'highlights' => ['Üniversite ve öğrenci odaklı pazar', 'Online sipariş ve teslimat beklentisi', 'Kiralık konut ve emlak ilan yapısı', 'Sosyal medyadan siteye akış'],
                'highlights_en' => ['University and student-driven market', 'Expectation of online ordering and delivery', 'Rental property listings', 'Flow from social media to the site'],
                'body' => '<p>Gazimağusa, iki büyük üniversitenin ve liman ekonomisinin şekillendirdiği bir şehir. Nüfusun önemli bölümü genç, dijitalde yaşıyor ve alışkanlıkları buna göre.</p><h2>Genç müşteri telefonla aramaz</h2><p>Magosa\'da kafe, market, kırtasiye ya da kuaför işletmesi için asıl kanal sosyal medya. Ama Instagram bir katalog değil: ürün listesi, fiyat, stok ve sipariş orada yönetilemiyor. Sosyal medyadan siteye geçiş burada en çok işe yarayan kurgu.</p><h3>Bu şehirde sık kurduğumuz yapılar</h3><ul><li>Online sipariş + teslimat bölgesi seçimi</li><li>Kiralık daire / stüdyo ilan listesi, filtreli</li><li>Dönemlik kampanya sayfaları — kayıt haftası, dönem başı</li><li>İngilizce sürüm: uluslararası öğrenci nüfusu ciddi büyüklükte</li></ul><h2>Hangi paket uygun</h2><p>Ürün satan işletmeler için E-Ticaret paketi doğrudan karşılık veriyor. Sadece menü ve konum gösterecek işletmeler Basic ya da Kurumsal + katalog modülüyle ilerliyor.</p>',
                'body_en' => '<p>Famagusta is shaped by two large universities and a port economy. A significant part of the population is young, lives online, and behaves accordingly.</p><h2>Young customers do not phone</h2><p>For a cafe, shop, stationer or salon in Famagusta the primary channel is social media. But Instagram is not a catalogue: product lists, prices, stock and orders cannot be managed there. Moving people from social media to the site is what works best here.</p><h3>What we build most often in this city</h3><ul><li>Online ordering with delivery zone selection</li><li>Filterable rental listings for flats and studios</li><li>Seasonal campaign pages — registration week, term start</li><li>An English version: the international student population is substantial</li></ul><h2>Which package fits</h2><p>For businesses selling products the E-Commerce package answers directly. Businesses that only need to show a menu and location go with Basic or Corporate plus the catalogue module.</p>',
                'seo_title' => 'Gazimağusa Web Tasarım | E-Ticaret ve Online Sipariş',
                'seo_title_en' => 'Web Design in Famagusta | E-Commerce and Online Ordering',
                'seo_description' => 'Gazimağusa\'da e-ticaret, online sipariş ve ilan siteleri. Öğrenci pazarına uygun, mobil öncelikli ve İngilizce destekli yapı.',
                'seo_description_en' => 'E-commerce, online ordering and listing sites in Famagusta. Mobile-first and English-ready for the student market.',
            ],
            [
                'slug' => 'guzelyurt',
                'name' => 'Güzelyurt',
                'name_en' => 'Morphou',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.1989,
                'longitude' => 32.9925,
                'headline' => 'Güzelyurt web tasarım',
                'headline_en' => 'Web design in Morphou',
                'intro' => 'Narenciye, tarım ve aile işletmeleri. Güzelyurt\'ta ihtiyaç karmaşık bir sistem değil; ürünü gösteren, güven veren ve WhatsApp\'a bağlayan sade bir site.',
                'intro_en' => 'Citrus, agriculture and family businesses. Morphou does not need a complex system — it needs a simple site that shows the product, builds trust and connects to WhatsApp.',
                'highlights' => ['Tarım ve gıda üreticileri', 'Toptan alıcıya yönelik ürün vitrini', 'WhatsApp üzerinden sipariş', 'Düşük bütçeli, hızlı teslim'],
                'highlights_en' => ['Agriculture and food producers', 'Product showcase aimed at wholesale buyers', 'Ordering over WhatsApp', 'Low budget, fast delivery'],
                'body' => '<p>Güzelyurt ekonomisi tarım ve gıda üretimi etrafında dönüyor. Buradaki işletmelerin çoğu aile şirketi; alıcıları da genelde toptancı ya da düzenli müşteri.</p><h2>Burada e-ticaret şart değil</h2><p>Online tahsilat çoğu Güzelyurt işletmesi için gereksiz maliyet. Alıcı ürünü görmek, fiyatı sormak ve sizi telefonla bulmak istiyor. Bu durumda doğru çözüm <strong>Kurumsal paket + katalog modülü</strong>: ürünler listeleniyor, sipariş WhatsApp\'tan geliyor, ödeme sistemine para harcanmıyor.</p><h3>Öne çıkan ihtiyaçlar</h3><ul><li>Ürün / çeşit vitrini: fotoğraf, kısa açıklama, sezon bilgisi</li><li>Üretim ve tesis hakkında güven veren bir sayfa</li><li>Toptan alıcı için net iletişim ve konum</li><li>Hızlı teslim: Hızlı Başlangıç paketi 3-5 iş gününde yayında</li></ul>',
                'body_en' => '<p>Morphou\'s economy revolves around agriculture and food production. Most businesses here are family firms, and their buyers are usually wholesalers or regular customers.</p><h2>E-commerce is not required here</h2><p>Online payment is an unnecessary cost for most Morphou businesses. The buyer wants to see the product, ask the price and reach you by phone. The right answer is <strong>the Corporate package plus the catalogue module</strong>: products are listed, orders arrive on WhatsApp, and no money goes into a payment system.</p><h3>Common needs</h3><ul><li>A product showcase: photo, short description, season information</li><li>A page about production and facilities that builds trust</li><li>Clear contact and location details for wholesale buyers</li><li>Fast delivery: the Quick Start package goes live in 3-5 working days</li></ul>',
                'seo_title' => 'Güzelyurt Web Tasarım | Ürün Vitrini ve Katalog Siteleri',
                'seo_title_en' => 'Web Design in Morphou | Product Showcase and Catalogue Sites',
                'seo_description' => 'Güzelyurt\'ta tarım ve gıda işletmeleri için ürün vitrini, katalog modülü ve WhatsApp sipariş. 3-5 iş gününde yayında.',
                'seo_description_en' => 'Product showcases, catalogue modules and WhatsApp ordering for agriculture and food businesses in Morphou. Live in 3-5 working days.',
            ],
            [
                'slug' => 'iskele',
                'name' => 'İskele',
                'name_en' => 'Iskele',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.2889,
                'longitude' => 33.8917,
                'headline' => 'İskele web tasarım',
                'headline_en' => 'Web design in Iskele',
                'intro' => 'KKTC\'nin en hızlı büyüyen bölgesi. İskele\'de site bir tanıtım aracı değil, doğrudan yatırımcı formu toplayan bir satış kanalı.',
                'intro_en' => 'The fastest-growing region in North Cyprus. In Iskele a site is not a brochure — it is a sales channel that collects investor enquiries.',
                'highlights' => ['İnşaat ve gayrimenkul projeleri', 'Yabancı yatırımcıya yönelik çok dilli yapı', 'Proje tanıtım ve talep formu', 'Reklam trafiğini karşılayan açılış sayfaları'],
                'highlights_en' => ['Construction and real estate projects', 'Multilingual for foreign investors', 'Project pages with enquiry forms', 'Landing pages built for ad traffic'],
                'body' => '<p>İskele bölgesi son yıllarda konut ve yatırım projeleriyle hızla büyüdü. Buradaki web ihtiyacı diğer şehirlerden yapısal olarak farklı: hedef kitle çoğunlukla bölge dışında, hatta ülke dışında.</p><h2>Site burada reklamın devamı</h2><p>Proje satışlarının önemli kısmı sosyal medya ve arama reklamlarıyla yürüyor. Reklamdan gelen ziyaretçi genel bir kurumsal ana sayfaya düşerse kayboluyor. Bunun yerine her proje için ayrı, tek amaçlı bir <strong>açılış sayfası</strong> gerekiyor: proje bilgisi, görseller, konum, ödeme planı ve tek bir form.</p><h3>Bu bölgede kritik olanlar</h3><ul><li>Proje bazlı sayfa yapısı — her proje kendi adresinde</li><li>Çok dilli içerik: İngilizce ve talebe göre Rusça</li><li>Talep formu + WhatsApp; yatırımcı hızlı dönüş bekliyor</li><li>Reklam ölçümü: hangi kampanya form getirdi, takip edilebilmeli</li></ul><h2>Hangi paket uygun</h2><p>Tek proje tanıtımı için Hızlı Başlangıç ya da Basic yeterli. Birden çok projesi olan firmalar, her projeyi kendi panelinden yönetebilmek için Kurumsal (panelli) tercih ediyor.</p>',
                'body_en' => '<p>The Iskele region has grown rapidly with housing and investment projects. The web requirement here is structurally different: the audience is mostly outside the region, often outside the country.</p><h2>The site is a continuation of the ad</h2><p>A large share of project sales runs through social and search advertising. A visitor arriving from an ad on a generic corporate homepage gets lost. What is needed instead is a separate, single-purpose <strong>landing page</strong> per project: project details, images, location, payment plan and one form.</p><h3>Critical in this region</h3><ul><li>Project-based structure — every project at its own address</li><li>Multilingual content: English, and Russian on request</li><li>Enquiry form plus WhatsApp; investors expect a fast reply</li><li>Ad measurement: which campaign produced the enquiry must be traceable</li></ul><h2>Which package fits</h2><p>For a single project, Quick Start or Basic is enough. Firms with several projects choose Corporate with a panel so they can manage each project themselves.</p>',
                'seo_title' => 'İskele Web Tasarım | Proje Tanıtım ve Gayrimenkul Siteleri',
                'seo_title_en' => 'Web Design in Iskele | Project and Real Estate Sites',
                'seo_description' => 'İskele\'de gayrimenkul projeleri için çok dilli açılış sayfaları, talep formu ve reklam uyumlu yapı. Panelden yönetilebilir proje sayfaları.',
                'seo_description_en' => 'Multilingual landing pages, enquiry forms and ad-ready structure for property projects in Iskele. Project pages you manage yourself.',
            ],
            [
                'slug' => 'lefke',
                'name' => 'Lefke',
                'name_en' => 'Lefke',
                'region' => 'kktc',
                'country_code' => 'CY',
                'latitude' => 35.1103,
                'longitude' => 32.8464,
                'headline' => 'Lefke web tasarım',
                'headline_en' => 'Web design in Lefke',
                'intro' => 'Küçük ölçekli, üniversite ve tarım ağırlıklı bir pazar. Lefke\'de doğru yatırım büyük bir sistem değil, hızlı yayına giren sade bir site.',
                'intro_en' => 'A small market driven by the university and agriculture. In Lefke the right investment is not a large system but a simple site that goes live fast.',
                'highlights' => ['Üniversite çevresi ve yerel esnaf', 'Tek sayfalık tanıtım genelde yeterli', 'Google haritada görünürlük öncelikli', 'En düşük bütçeyle yayına çıkma'],
                'highlights_en' => ['University community and local trade', 'A single page is usually enough', 'Visibility on Google Maps comes first', 'Going live on the smallest budget'],
                'body' => '<p>Lefke, nüfusu görece küçük ama üniversitesi ve tarımsal üretimiyle kendine özgü bir pazar. Buradaki işletmeler için büyük bütçeli bir proje çoğu zaman gereksiz.</p><h2>Önce haritada görünmek</h2><p>Lefke ölçeğinde bir işletme için ilk kazanç web sitesinden değil, <strong>Google Business Profile</strong>\'dan geliyor: doğru kategori, güncel çalışma saatleri, gerçek fotoğraflar ve yorumlara verilen cevaplar. Site bunu tamamlayan ikinci adım.</p><h3>Uygun kurulum</h3><ul><li>Tek sayfalık tanıtım: ne yaptığınız, nerede olduğunuz, nasıl ulaşılacağı</li><li>WhatsApp butonu ve harita</li><li>Google Business Profile kurulumu ve site ile tutarlı bilgiler</li><li>Hızlı Başlangıç paketi — 3-5 iş gününde yayında</li></ul>',
                'body_en' => '<p>Lefke has a relatively small population but a distinct market shaped by its university and agricultural production. A large-budget project is usually unnecessary for businesses here.</p><h2>Appear on the map first</h2><p>At Lefke\'s scale the first return comes not from the website but from the <strong>Google Business Profile</strong>: the right category, current opening hours, real photos and replies to reviews. The site is the second step that completes it.</p><h3>A suitable setup</h3><ul><li>A single page: what you do, where you are, how to reach you</li><li>WhatsApp button and map</li><li>Google Business Profile setup, consistent with the site</li><li>The Quick Start package — live in 3-5 working days</li></ul>',
                'seo_title' => 'Lefke Web Tasarım | Tek Sayfa Site ve Yerel SEO',
                'seo_title_en' => 'Web Design in Lefke | Single-Page Sites and Local SEO',
                'seo_description' => 'Lefke\'de tek sayfalık tanıtım sitesi, Google Business Profile kurulumu ve yerel SEO. 3-5 iş gününde yayında, 6.900 ₺\'den başlayan fiyatlarla.',
                'seo_description_en' => 'Single-page sites, Google Business Profile setup and local SEO in Lefke. Live in 3-5 working days.',
            ],

            /* ── Türkiye ────────────────────────────────────────────────── */
            [
                'slug' => 'istanbul',
                'name' => 'İstanbul',
                'name_en' => 'Istanbul',
                'region' => 'turkiye',
                'country_code' => 'TR',
                'latitude' => 41.0082,
                'longitude' => 28.9784,
                'headline' => 'İstanbul web tasarım',
                'headline_en' => 'Web design for Istanbul',
                'intro' => 'İstanbul\'da ajans bolluğu var ama fiyat aralığı çok geniş. Kıbrıs merkezli çalışıyoruz: ajans kalitesi, İstanbul ajans fiyatının altında.',
                'intro_en' => 'Istanbul has no shortage of agencies, but the price range is enormous. We work from Cyprus: agency quality below Istanbul agency pricing.',
                'highlights' => ['E-ticaret yoğun, rekabet yüksek', 'Uzaktan çalışma — süreç online yürüyor', 'Ajans kalitesi, daha düşük maliyet', 'Sınırsız ürün ve gelişmiş panel ihtiyacı'],
                'highlights_en' => ['E-commerce heavy, highly competitive', 'Remote working — the process runs online', 'Agency quality at lower cost', 'Need for unlimited products and an advanced panel'],
                'body' => '<p>İstanbul, Türkiye\'nin e-ticaret hacminin büyük bölümünü barındırıyor. Rekabet de aynı oranda yüksek: aynı işe 15.000 ₺ de teklif geliyor, 400.000 ₺ de.</p><h2>Uzaktan çalışmak sorun değil</h2><p>Merkezimiz Kuzey Kıbrıs. Süreç tamamen online yürüyor: brief görüşmesi, akış onayı, tasarım sunumu ve teslim eğitimi görüntülü toplantıyla. İstanbul\'daki müşterilerimiz için ofise gitmenin pratik bir karşılığı yok; buna karşılık maliyet farkı belirgin.</p><h3>İstanbul\'da sık karşılaştığımız ihtiyaçlar</h3><ul><li>Sınırsız ürün, varyant ve kampanya yönetimi</li><li>Kargo ve ödeme entegrasyonlarının sorunsuz çalışması</li><li>Sayfa hızı — reklam maliyeti yüksek olduğu için her saniye para</li><li>Mevcut siteden içerik ve SEO değeri kaybetmeden taşınma</li></ul><h2>Fiyat farkı nereden geliyor</h2><p>Üretim maliyetimiz TL bazlı ve ekip yapımız küçük. Aynı işi ara katman olmadan yapıyoruz; İstanbul ajanslarının ofis ve satış ekibi maliyeti fiyatımıza binmiyor. Paket fiyatlarımız sitede açıkça yazılı.</p>',
                'body_en' => '<p>Istanbul accounts for a large share of Türkiye\'s e-commerce volume. Competition is proportionally fierce: the same job gets quoted at 15,000 ₺ and at 400,000 ₺.</p><h2>Working remotely is not a problem</h2><p>We are based in North Cyprus and the process runs entirely online: brief, flow approval, design presentation and handover training over video. For our Istanbul clients an office visit has no practical value — while the cost difference is significant.</p><h3>What Istanbul clients usually need</h3><ul><li>Unlimited products, variants and campaign management</li><li>Shipping and payment integrations that simply work</li><li>Page speed — with high ad costs, every second is money</li><li>Migrating from an existing site without losing content or SEO value</li></ul><h2>Where the price difference comes from</h2><p>Our production costs are in Turkish lira and our team is small. We do the same work without intermediaries; the office and sales overhead of Istanbul agencies is not added to your price. Our package prices are written openly on the site.</p>',
                'seo_title' => 'İstanbul Web Tasarım ve E-Ticaret | Kıbrıs Merkezli Stüdyo',
                'seo_title_en' => 'Web Design and E-Commerce for Istanbul | Cyprus-Based Studio',
                'seo_description' => 'İstanbul\'a uzaktan web tasarım ve e-ticaret hizmeti. Sınırsız ürün, gelişmiş panel, entegrasyonlar. Fiyatlar açıkça yazılı, ajans fiyatının altında.',
                'seo_description_en' => 'Remote web design and e-commerce for Istanbul. Unlimited products, advanced panel, integrations. Prices written openly.',
            ],
            [
                'slug' => 'ankara',
                'name' => 'Ankara',
                'name_en' => 'Ankara',
                'region' => 'turkiye',
                'country_code' => 'TR',
                'latitude' => 39.9334,
                'longitude' => 32.8597,
                'headline' => 'Ankara web tasarım',
                'headline_en' => 'Web design for Ankara',
                'intro' => 'Ankara\'da iş çoğunlukla B2B: kamu tedarikçisi, mühendislik, savunma yan sanayi ve danışmanlık. Site burada ihale dosyasının bir parçası.',
                'intro_en' => 'Business in Ankara is mostly B2B: public-sector suppliers, engineering, defence subcontractors and consultancies. Here the site is part of the tender file.',
                'highlights' => ['B2B ve kamu tedarik ekosistemi', 'Referans, belge ve sertifika sayfaları', 'İngilizce sürüm ihracat için', 'Kurumsal ciddiyet, gösterişten uzak tasarım'],
                'highlights_en' => ['B2B and public procurement ecosystem', 'Reference, document and certificate pages', 'English version for exports', 'Corporate seriousness over flash'],
                'body' => '<p>Ankara\'daki müşteri profili İstanbul\'dan belirgin şekilde farklı. Satış nadiren siteden doğrudan geliyor; site daha çok <strong>yeterlilik kanıtı</strong> olarak çalışıyor.</p><h2>İhale ve tedarik süreçlerinde site</h2><p>Bir kamu kurumuna ya da büyük bir ana yükleniciye teklif verirken karşı taraf firmayı araştırıyor. O anda sitede görmek istedikleri belli: hangi işleri yaptınız, hangi belgelere sahipsiniz, ekip ne kadar ciddi, iletişim gerçek mi.</p><h3>Bu profilde önemli olanlar</h3><ul><li>Referans ve tamamlanan iş listesi — abartısız, doğrulanabilir</li><li>Belge, sertifika ve kalite politikası sayfaları</li><li>Hizmet detay sayfaları: teknik ve net, pazarlama dili az</li><li>İngilizce sürüm — ihracat ve uluslararası ortaklıklar için</li></ul><h2>Hangi paket uygun</h2><p>Bu yapı çok sayfa ve düzenli içerik güncellemesi gerektiriyor. Ankara\'daki B2B firmalar çoğunlukla Kurumsal (panelli) paketle ilerliyor.</p>',
                'body_en' => '<p>The client profile in Ankara differs markedly from Istanbul. Sales rarely come directly from the site; the site works as <strong>proof of capability</strong>.</p><h2>The site in tender and procurement</h2><p>When you bid to a public body or a large prime contractor, they research the company. What they want to see is specific: which projects you have delivered, which certifications you hold, how serious the team is, whether the contact details are real.</p><h3>What matters for this profile</h3><ul><li>A reference list of completed work — modest and verifiable</li><li>Certificates and quality policy pages</li><li>Service detail pages: technical and clear, light on marketing language</li><li>An English version — for exports and international partnerships</li></ul><h2>Which package fits</h2><p>This structure needs multiple pages and regular content updates. B2B firms in Ankara usually go with the Corporate package with a panel.</p>',
                'seo_title' => 'Ankara Web Tasarım | B2B ve Kurumsal Siteler',
                'seo_title_en' => 'Web Design for Ankara | B2B and Corporate Sites',
                'seo_description' => 'Ankara\'daki B2B ve kamu tedarikçisi firmalar için kurumsal web sitesi: referans, belge ve hizmet detay sayfaları, İngilizce sürüm.',
                'seo_description_en' => 'Corporate websites for B2B and public-sector suppliers in Ankara: references, certifications and service pages, with an English version.',
            ],
            [
                'slug' => 'izmir',
                'name' => 'İzmir',
                'name_en' => 'Izmir',
                'region' => 'turkiye',
                'country_code' => 'TR',
                'latitude' => 38.4237,
                'longitude' => 27.1428,
                'headline' => 'İzmir web tasarım',
                'headline_en' => 'Web design for Izmir',
                'intro' => 'İhracat şehri. İzmir\'de tekstil, gıda ve zeytinyağı üreticileri için site yurt dışı alıcının ilk durağı — o yüzden İngilizce sürüm pazarlık konusu değil.',
                'intro_en' => 'An export city. For textile, food and olive oil producers in Izmir the site is the first stop for a foreign buyer — which makes an English version non-negotiable.',
                'highlights' => ['İhracatçı üretici profili', 'İngilizce şart, Almanca sık talep', 'Ürün kataloğu ve teknik döküman', 'Fuar ve alıcı yönlendirmeli yapı'],
                'highlights_en' => ['Exporting manufacturers', 'English essential, German often requested', 'Product catalogues and technical documents', 'Built around trade fairs and buyer journeys'],
                'body' => '<p>İzmir ekonomisinin belirgin bir kısmı ihracata dayanıyor: tekstil, hazır giyim, gıda, zeytinyağı ve tarım ürünleri. Bu, web sitesinin işlevini doğrudan değiştiriyor.</p><h2>Alıcı yurt dışında, ilk izlenim sitede</h2><p>Yurt dışındaki bir alıcı sizi fuarda ya da bir B2B platformunda buluyor, sonra siteye bakıyor. Türkçe tek dilli, üretim kapasitesi belirsiz bir site o noktada süreci bitiriyor. İngilizce sürüm, kapasite bilgisi ve teknik döküman burada satış aracı.</p><h3>İhracatçılar için kurduğumuz yapı</h3><ul><li>İngilizce sürüm — Kurumsal pakette zaten dahil</li><li>Ürün kataloğu: teknik özellik, paketleme, minimum sipariş bilgisi</li><li>Üretim tesisi ve kapasite sayfası, gerçek fotoğraflarla</li><li>Fuar takvimi ve iletişim; alıcı sizi fuardan sonra buradan buluyor</li></ul><h2>Yurt içi satış da varsa</h2><p>Hem ihracat hem yurt içi perakende yapan üreticiler için E-Ticaret paketiyle birleşik bir yapı kuruyoruz: dışa dönük katalog, içe dönük satış.</p>',
                'body_en' => '<p>A clear share of Izmir\'s economy rests on exports: textiles, apparel, food, olive oil and agricultural products. That changes what the website is for.</p><h2>The buyer is abroad; first impressions happen on the site</h2><p>A foreign buyer finds you at a trade fair or on a B2B platform, then looks at the site. A Turkish-only site with unclear production capacity ends the process there. An English version, capacity information and technical documents are the sales tools here.</p><h3>What we build for exporters</h3><ul><li>An English version — already included in the Corporate package</li><li>A product catalogue: specifications, packaging, minimum order</li><li>A production facility and capacity page with real photographs</li><li>Trade fair calendar and contact details</li></ul><h2>If you also sell domestically</h2><p>For manufacturers doing both export and domestic retail we build a combined structure with the E-Commerce package: an outward-facing catalogue and inward-facing sales.</p>',
                'seo_title' => 'İzmir Web Tasarım | İhracatçı ve Üretici Siteleri',
                'seo_title_en' => 'Web Design for Izmir | Exporter and Manufacturer Sites',
                'seo_description' => 'İzmir\'deki ihracatçı üreticiler için İngilizce destekli kurumsal site, ürün kataloğu ve e-ticaret. Fiyatlar açıkça yazılı.',
                'seo_description_en' => 'English-ready corporate sites, product catalogues and e-commerce for exporters in Izmir. Prices written openly.',
            ],
            [
                'slug' => 'antalya',
                'name' => 'Antalya',
                'name_en' => 'Antalya',
                'region' => 'turkiye',
                'country_code' => 'TR',
                'latitude' => 36.8969,
                'longitude' => 30.7133,
                'headline' => 'Antalya web tasarım',
                'headline_en' => 'Web design for Antalya',
                'intro' => 'Turizm ve yabancıya konut satışı. Antalya\'da tek dilli site pazarın büyük kısmını görmezden gelmek demek.',
                'intro_en' => 'Tourism and property sales to foreign buyers. In Antalya a single-language site ignores most of the market.',
                'highlights' => ['Otel, transfer ve tur işletmeleri', 'Çok dilli: EN, RU, DE talebi yüksek', 'Rezervasyon ve talep formu akışı', 'Yabancıya gayrimenkul satış sayfaları'],
                'highlights_en' => ['Hotels, transfers and tour operators', 'Multilingual: EN, RU and DE in demand', 'Booking and enquiry flows', 'Property pages aimed at foreign buyers'],
                'body' => '<p>Antalya\'da iki büyük dijital pazar var: turizm hizmetleri ve yabancıya gayrimenkul satışı. İkisinin de ortak noktası müşterinin Türkçe konuşmuyor olması.</p><h2>Dil sayısı doğrudan gelir kalemi</h2><p>Bir transfer firması ya da butik otel için Rusça ve Almanca sürüm, çoğu zaman reklam bütçesinden daha yüksek getiri sağlıyor. Sitemizin altyapısı çoklu dili destekliyor; her ek dil bir modül olarak ekleniyor.</p><h3>Antalya\'da sık kurduğumuz yapılar</h3><ul><li>Rezervasyon / transfer talep formu — tarih, kişi, güzergâh</li><li>Çok dilli içerik yönetimi; her dili panelden kendiniz güncelleyin</li><li>Gayrimenkul portföyü: filtreli liste, konum, ödeme planı</li><li>Reklam kampanyalarına özel açılış sayfaları</li></ul><h2>Sezon öncesi teslim</h2><p>Turizmde takvim sabit. Sezon açılmadan yayına girmek için Basic 4-6, Kurumsal 8-12 iş gününde teslim ediliyor; planlamayı buna göre yapıyoruz.</p>',
                'body_en' => '<p>Antalya has two large digital markets: tourism services and property sales to foreign buyers. What they share is that the customer does not speak Turkish.</p><h2>The number of languages is a revenue line</h2><p>For a transfer company or boutique hotel, Russian and German versions often return more than the advertising budget. Our infrastructure supports multiple languages; each additional language is added as a module.</p><h3>What we build most often in Antalya</h3><ul><li>Booking and transfer request forms — date, passengers, route</li><li>Multilingual content management you update yourself</li><li>Property portfolios: filterable lists, location, payment plans</li><li>Dedicated landing pages for ad campaigns</li></ul><h2>Delivery before the season</h2><p>Tourism runs on a fixed calendar. To go live before the season opens, Basic ships in 4-6 and Corporate in 8-12 working days; we plan around that.</p>',
                'seo_title' => 'Antalya Web Tasarım | Turizm ve Gayrimenkul Siteleri',
                'seo_title_en' => 'Web Design for Antalya | Tourism and Property Sites',
                'seo_description' => 'Antalya\'da otel, transfer ve gayrimenkul firmaları için çok dilli web sitesi, rezervasyon formu ve açılış sayfaları. Sezon öncesi teslim.',
                'seo_description_en' => 'Multilingual websites, booking forms and landing pages for hotels, transfers and property firms in Antalya. Delivered before the season.',
            ],
            [
                'slug' => 'bursa',
                'name' => 'Bursa',
                'name_en' => 'Bursa',
                'region' => 'turkiye',
                'country_code' => 'TR',
                'latitude' => 40.1826,
                'longitude' => 29.0665,
                'headline' => 'Bursa web tasarım',
                'headline_en' => 'Web design for Bursa',
                'intro' => 'Otomotiv yan sanayi, tekstil ve makine. Bursa\'da site son tüketiciye değil, bayiye ve ana sanayiye konuşuyor.',
                'intro_en' => 'Automotive supply, textiles and machinery. In Bursa the site talks to dealers and prime manufacturers, not end consumers.',
                'highlights' => ['Sanayi ve yan sanayi üreticileri', 'Bayi / müşteri portalı ihtiyacı', 'Teknik ürün kataloğu ve döküman', 'B2B fiyat listesi ve sipariş akışı'],
                'highlights_en' => ['Industrial and subcontract manufacturers', 'Dealer and customer portal needs', 'Technical catalogues and documents', 'B2B price lists and ordering'],
                'body' => '<p>Bursa\'nın dijital ihtiyacı büyük ölçüde sanayi yapısından geliyor: otomotiv yan sanayi, tekstil ve makine imalatı. Bu firmaların müşterisi son tüketici değil.</p><h2>B2B\'de site bir araç, vitrin değil</h2><p>Bayisi ya da düzenli kurumsal müşterisi olan bir üretici için asıl kazanç, telefon ve e-posta trafiğini azaltan bir <strong>portal</strong>: bayi giriş yapıyor, kendi fiyat listesini görüyor, sipariş açıyor, geçmişini takip ediyor.</p><h3>Bursa\'da sık yaptığımız işler</h3><ul><li>Bayi / müşteri portalı: rol bazlı yetki, özel fiyat listesi</li><li>Teknik ürün kataloğu: ölçü tabloları, PDF döküman indirme</li><li>Mevcut ERP ya da muhasebe sistemine API bağlantısı</li><li>İngilizce sürüm — ihracat yapan yan sanayi için</li></ul><h2>Hangi hizmet uygun</h2><p>Bu ihtiyaçlar hazır bir paketle karşılanmıyor; Özel Web Yazılımı hizmetiyle ilerliyoruz. Kapsamı görüşmede netleştirip sabit fiyatlı teklif veriyoruz.</p>',
                'body_en' => '<p>Bursa\'s digital needs come largely from its industrial base: automotive supply, textiles and machinery manufacturing. These firms do not sell to end consumers.</p><h2>In B2B the site is a tool, not a showcase</h2><p>For a manufacturer with dealers or regular corporate customers, the real gain is a <strong>portal</strong> that reduces phone and email traffic: the dealer logs in, sees their own price list, places an order and tracks history.</p><h3>What we build most often in Bursa</h3><ul><li>Dealer and customer portals: role-based permissions, custom price lists</li><li>Technical product catalogues: dimension tables, downloadable PDFs</li><li>API connections to an existing ERP or accounting system</li><li>An English version — for exporting subcontractors</li></ul><h2>Which service fits</h2><p>These needs are not met by an off-the-shelf package; we work through the Custom Web Software service. We scope it on a call and send a fixed-price proposal.</p>',
                'seo_title' => 'Bursa Web Tasarım | Bayi Portalı ve Sanayi Siteleri',
                'seo_title_en' => 'Web Design for Bursa | Dealer Portals and Industrial Sites',
                'seo_description' => 'Bursa\'daki sanayi ve yan sanayi firmaları için bayi portalı, teknik ürün kataloğu ve ERP entegrasyonu. Özel web yazılımı.',
                'seo_description_en' => 'Dealer portals, technical catalogues and ERP integration for industrial firms in Bursa. Custom web software.',
            ],
        ];
    }
}
