<?php

namespace Database\Seeders;

use App\Models\Sector;
use Illuminate\Database\Seeder;

/**
 * Sektör sayfaları.
 *
 * Buradaki metinler şehir sayfalarının aksine gerçekten birbirinden farklı,
 * çünkü ihtiyaçlar gerçekten farklı: otel rezervasyon alır, emlakçı ilan
 * yayınlar, restoran menü gösterir, sanayi firması bayiye şifreli fiyat verir.
 *
 * Kural: uydurma referans, müşteri sayısı, "sektör lideri" iddiası YOK. Yazılan
 * her şey ya hizmet tanımı ya da o sektörde herkesin bildiği bir gözlem.
 */
class SectorSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->sectors() as $i => $sector) {
            Sector::query()->updateOrCreate(
                ['slug' => $sector['slug']],
                $sector + ['sort_order' => $i + 1, 'is_active' => true],
            );
        }
    }

    private function sectors(): array
    {
        return [
            [
                'slug' => 'otel-ve-konaklama',
                'name' => 'Otel & Konaklama',
                'name_en' => 'Hotels & Hospitality',
                'icon' => '🏨',
                'headline' => 'Otel web sitesi',
                'headline_en' => 'Hotel websites',
                'intro' => 'Otelin sitesi bir katalog değil, rezervasyon kanalı. Misafiri acentaya kaptırmadan doğrudan size getirmesi gerekir.',
                'intro_en' => 'A hotel site is not a brochure, it is a booking channel. It has to bring the guest to you directly instead of losing them to an OTA.',
                'needs' => [
                    'Misafirin yarısı sizi Türkçe aramıyor — çok dilli olmak şart',
                    'Fotoğraf ağırlıklı ama mobilde saniyeler içinde açılan yapı',
                    'Müsaitlik ve rezervasyon talebi tek adımda',
                    'Booking/Airbnb komisyonunu düşüren doğrudan kanal',
                ],
                'needs_en' => [
                    'Half your guests are not searching in Turkish — multilingual is mandatory',
                    'Photo-heavy but opens in seconds on mobile',
                    'Availability and booking request in a single step',
                    'A direct channel that cuts OTA commission',
                ],
                'features' => [
                    'Oda tipleri, kapasite ve donanım listesi',
                    'Tarih seçmeli rezervasyon talep formu',
                    'Galeri: sıkıştırılmış, hızlı yüklenen görseller',
                    'Konum, ulaşım ve çevre bilgisi',
                    'WhatsApp\'a tek dokunuşla bağlanan iletişim',
                    'Google Business Profile ile uyumlu bilgi yapısı',
                ],
                'features_en' => [
                    'Room types, capacity and amenity lists',
                    'Booking request form with date selection',
                    'Gallery with compressed, fast-loading images',
                    'Location, transport and neighbourhood information',
                    'One-tap WhatsApp contact',
                    'Information structure aligned with Google Business Profile',
                ],
                'body' => '<p>Konaklama işinde sitenin görevi net: misafir Booking\'de sizi bulduktan sonra adınızı Google\'a yazıyor. O anda karşısına çıkan sayfa, aracı komisyonu ödemeden rezervasyon alabileceğiniz tek yer.</p><h2>Çok dillilik lüks değil</h2><p>Kıbrıs ve Antalya gibi pazarlarda trafiğin önemli kısmı Türkçe dışında geliyor. Tek dilli bir site, bu trafiğin tamamını görmezden gelmek demek. Altyapı çok dilli kuruluyor; yabancı dil eklemek isteğe bağlı bir seçenek.</p><h2>Hız, fotoğraftan önce gelir</h2><p>Otel siteleri görsel ağırlıklıdır ve çoğu bu yüzden yavaştır. Görselleri modern formatlarda sıkıştırıp tembel yüklüyoruz: sayfa açılırken sadece ekranda görünen fotoğraflar iniyor. Misafirin telefonu ve otel wifi\'si buna teşekkür ediyor.</p><h3>Rezervasyon akışı</h3><p>Tam otomatik ödeme alan bir motor mu, yoksa tarih ve kişi sayısı toplayıp size düşen bir talep formu mu — bu bir bütçe kararı. Küçük ve butik işletmelerde talep formu genelde yeterli oluyor; oda sayısı arttıkça takvimli sisteme geçmek mantıklı hâle geliyor. İkisini de yapıyoruz, hangisinin gerektiğini görüşmede konuşuyoruz.</p>',
                'body_en' => '<p>In hospitality the job of the site is clear: after finding you on an OTA, the guest types your name into Google. The page they land on is the only place you can take a booking without paying commission.</p><h2>Multilingual is not a luxury</h2><p>In markets like Cyprus and Antalya a large share of traffic arrives in languages other than Turkish. A single-language site ignores all of it. Every build is multilingual-ready; adding a foreign language is an option.</p><h2>Speed comes before photography</h2><p>Hotel sites are image-heavy and most of them are slow for exactly that reason. We compress images into modern formats and load them lazily: only what is on screen downloads first. The guest\'s phone and the hotel wifi both benefit.</p><h3>The booking flow</h3><p>A full engine that takes payment, or a request form that collects dates and guest count and lands in your inbox — that is a budget decision. For small and boutique properties a request form is usually enough; as room count grows a calendar-based system starts to make sense. We build both.</p>',
                'seo_title' => 'Otel Web Sitesi Tasarımı | Rezervasyon Alan, Çok Dilli Site',
                'seo_title_en' => 'Hotel Website Design | Multilingual Sites That Take Bookings',
                'seo_description' => 'Otel ve konaklama işletmeleri için çok dilli, hızlı ve rezervasyon talebi toplayan web sitesi. Oda tipleri, galeri, müsaitlik formu. Fiyatlar açık.',
                'seo_description_en' => 'Multilingual, fast websites that collect booking requests for hotels and guesthouses. Room types, gallery, availability form. Prices published openly.',
            ],

            [
                'slug' => 'restoran-ve-kafe',
                'name' => 'Restoran & Kafe',
                'name_en' => 'Restaurants & Cafés',
                'icon' => '🍽️',
                'headline' => 'Restoran web sitesi',
                'headline_en' => 'Restaurant websites',
                'intro' => 'Müşteri menüyü telefonundan bakıyor, rezervasyonu WhatsApp\'tan yapıyor. Site bu iki işi kusursuz yapmalı, gerisi süs.',
                'intro_en' => 'Guests read the menu on their phone and book over WhatsApp. The site has to nail those two jobs; the rest is decoration.',
                'needs' => [
                    'Menü PDF değil, telefonda okunabilir sayfa olmalı',
                    'Fiyat değişince siteyi beklemeden kendiniz güncelleyebilmelisiniz',
                    'Rezervasyon ve paket sipariş için tek dokunuş',
                    'Google Haritalar ve çalışma saatleri her zaman doğru',
                ],
                'needs_en' => [
                    'The menu must be a readable page, not a PDF',
                    'You should update prices yourself, without waiting for anyone',
                    'One tap for reservations and takeaway orders',
                    'Google Maps and opening hours always accurate',
                ],
                'features' => [
                    'Panelden yönetilen menü: kategori, ürün, fiyat, alerjen',
                    'QR menü olarak da kullanılabilen mobil görünüm',
                    'Rezervasyon formu ve WhatsApp sipariş bağlantısı',
                    'Günün menüsü / kampanya duyuru alanı',
                    'Çalışma saatleri ve konum bloğu',
                    'Instagram akışına bağlantı',
                ],
                'features_en' => [
                    'Menu managed from the panel: categories, items, prices, allergens',
                    'Mobile view that doubles as a QR menu',
                    'Reservation form and WhatsApp ordering link',
                    'Daily special / campaign announcement area',
                    'Opening hours and location block',
                    'Link to the Instagram feed',
                ],
                'body' => '<p>Restoran sitelerinde en sık yapılan hata menüyü PDF olarak koymak. Telefonda açılan PDF\'i okumak için yakınlaştırma yapmak gerekiyor, arama motorları içindeki ürün adlarını göremiyor ve fiyat değiştiğinde yeni dosya hazırlamak zorunda kalıyorsunuz.</p><h2>Menü bir sayfa olmalı</h2><p>Menüyü panelden yönetilen bir yapı olarak kuruyoruz: kategori ekliyor, ürün yazıyor, fiyatı değiştiriyorsunuz. Değişiklik anında yayında. Aynı sayfa telefonda QR menü olarak da çalışıyor, masaya ayrı bir sistem kurmanız gerekmiyor.</p><h2>Sipariş nereden geliyor</h2><p>Kıbrıs\'ta ve Türkiye\'nin çoğu şehrinde paket sipariş hâlâ ağırlıklı olarak telefon ve WhatsApp üzerinden. Bu yüzden siteyi sepetli bir sistemle karmaşıklaştırmadan önce, WhatsApp\'a ürün adıyla birlikte giden bir bağlantı çoğu işletme için daha iyi çalışıyor. Sipariş hacmi büyüdüğünde sepet ve online ödemeye geçmek her zaman mümkün.</p><h3>Yerel aramada görünmek</h3><p>"Yakınımdaki restoran" aramalarında çıkmanın yolu siteden çok Google Business Profile\'dan geçiyor. Sitedeki adres, telefon ve çalışma saati bilgisini oradaki kayıtla birebir aynı tutuyoruz — tutarsızlık yerel sıralamayı doğrudan düşürüyor.</p>',
                'body_en' => '<p>The most common mistake on restaurant sites is publishing the menu as a PDF. It requires pinch-zooming on a phone, search engines cannot read the dish names inside it, and every price change means producing a new file.</p><h2>The menu should be a page</h2><p>We build the menu as a panel-managed structure: you add categories, write items, change prices. Changes are live immediately. The same page works as a QR menu on the phone, so you do not need a separate system for the tables.</p><h2>Where orders actually come from</h2><p>In Cyprus and in most Turkish cities takeaway still arrives mainly by phone and WhatsApp. So before complicating the site with a cart, a link that opens WhatsApp pre-filled with the item name works better for most venues. Moving to a cart and online payment is always possible once volume grows.</p><h3>Showing up in local search</h3><p>Appearing in "restaurants near me" depends more on Google Business Profile than on the site. We keep the address, phone and opening hours on the site identical to that listing — inconsistency directly lowers local ranking.</p>',
                'seo_title' => 'Restoran & Kafe Web Sitesi | Panelden Yönetilen Menü',
                'seo_title_en' => 'Restaurant & Café Websites | Menus You Manage Yourself',
                'seo_description' => 'Restoran ve kafeler için mobilde hızlı, panelden güncellenen menülü web sitesi. QR menü, rezervasyon formu, WhatsApp sipariş bağlantısı.',
                'seo_description_en' => 'Fast mobile websites for restaurants and cafés with a self-managed menu. QR menu, reservation form, WhatsApp ordering.',
            ],

            [
                'slug' => 'emlak-ve-insaat',
                'name' => 'Emlak & İnşaat',
                'name_en' => 'Real Estate & Construction',
                'icon' => '🏗️',
                'headline' => 'Emlak ve inşaat web sitesi',
                'headline_en' => 'Real estate and construction websites',
                'intro' => 'Bu işte site bir vitrin değil, form toplayan bir satış kanalı. Ziyaretçinin ilanı bulup iletişime geçmesi arasındaki her adım kayıp.',
                'intro_en' => 'Here the site is a lead-generating sales channel, not a showroom. Every step between finding a listing and making contact is lost business.',
                'needs' => [
                    'İlan/proje listesi filtrelenebilir olmalı: bölge, tip, fiyat, oda',
                    'Yabancı alıcı için çok dilli sürüm ve para birimi',
                    'Her ilanda doğrudan iletişim ve WhatsApp',
                    'Proje ilerleme fotoğrafları ve teslim takvimi',
                ],
                'needs_en' => [
                    'Listings must be filterable: area, type, price, rooms',
                    'A multilingual version and currency options for foreign buyers',
                    'Direct contact and WhatsApp on every listing',
                    'Construction progress photos and delivery schedule',
                ],
                'features' => [
                    'Panelden yönetilen ilan/proje kayıtları',
                    'Filtre ve arama: bölge, oda sayısı, fiyat aralığı',
                    'İlan detayında galeri, kat planı, konum haritası',
                    'İlan başına talep formu — hangi ilandan geldiği kaydedilir',
                    'Satıldı / rezerve durumu',
                    'Çok dilli içerik ve döviz gösterimi',
                ],
                'features_en' => [
                    'Panel-managed listings and projects',
                    'Filter and search: area, rooms, price range',
                    'Gallery, floor plan and map on the listing detail',
                    'Per-listing enquiry form that records which listing it came from',
                    'Sold / reserved status',
                    'Multilingual content and currency display',
                ],
                'body' => '<p>Emlak ve inşaat, web sitesinin doğrudan paraya döndüğü nadir sektörlerden biri. Ziyaretçi zaten satın almaya niyetli geliyor; sitenin işi onu ilanı bulur bulmaz size ulaştırmak.</p><h2>Filtre olmadan olmaz</h2><p>Yirmi ilanı alt alta sıralamak yeterli değil. Ziyaretçi bölgeye, oda sayısına ve fiyat aralığına göre daraltamıyorsa listeyi terk ediyor. İlan sayısı arttıkça bu daha da belirginleşiyor.</p><h2>Talebin nereden geldiğini bilmek</h2><p>Genel bir "iletişim" formu, hangi ilanla ilgilenildiğini söylemez. Her ilana kendi formunu koyuyoruz; size gelen mesajda ilan adı ve bağlantısı hazır oluyor. Bu tek başına dönüş süresini ciddi biçimde kısaltıyor.</p><h3>Yabancı alıcı</h3><p>Kıbrıs\'ta ve Antalya\'da alıcının önemli kısmı yurt dışından. İngilizce şart; pazara göre Rusça veya Almanca da anlamlı oluyor. Fiyatları ikinci bir para biriminde göstermek, alıcının hesap yapmak için siteden çıkmasını engelliyor.</p><h3>İnşaat firmaları için fark</h3><p>Emlakçıda ilan, inşaatçıda proje var. Proje sayfalarında ilerleme fotoğrafları ve teslim tarihi, alıcıya "bu iş yürüyor" demenin en doğrudan yolu. Aynı yapı, tamamlanmış projeler için referans arşivi olarak da çalışıyor.</p>',
                'body_en' => '<p>Real estate and construction is one of the few sectors where a website turns into money directly. The visitor already intends to buy; the site\'s job is to connect them to you the moment they find the right listing.</p><h2>Filters are not optional</h2><p>Stacking twenty listings in a column is not enough. If a visitor cannot narrow by area, room count and price range, they leave. The more listings you have, the sharper this gets.</p><h2>Knowing where the enquiry came from</h2><p>A generic contact form does not tell you which property the person was looking at. We put a form on every listing; the message that reaches you already contains the listing name and link. That alone shortens response time considerably.</p><h3>Foreign buyers</h3><p>In Cyprus and Antalya a large share of buyers come from abroad. English is essential; depending on the market Russian or German can be worth adding. Showing prices in a second currency stops buyers leaving the site to do the maths.</p><h3>What differs for construction firms</h3><p>Agencies have listings, developers have projects. Progress photos and a delivery date on a project page are the most direct way of telling a buyer that the work is moving. The same structure later works as an archive of completed projects.</p>',
                'seo_title' => 'Emlak ve İnşaat Web Sitesi | Filtreli İlan ve Proje Sayfaları',
                'seo_title_en' => 'Real Estate & Construction Websites | Filterable Listings',
                'seo_description' => 'Emlak ofisleri ve inşaat firmaları için filtrelenebilir ilan/proje sistemi, ilan başına talep formu, çok dilli yapı ve döviz gösterimi.',
                'seo_description_en' => 'Filterable listing and project systems for agencies and developers, per-listing enquiry forms, multilingual structure and currency display.',
            ],

            [
                'slug' => 'e-ticaret-ve-perakende',
                'name' => 'E-Ticaret & Perakende',
                'name_en' => 'E-Commerce & Retail',
                'icon' => '🛒',
                'headline' => 'E-ticaret sitesi',
                'headline_en' => 'E-commerce stores',
                'intro' => 'Mağaza kurmak kolay, satan mağaza kurmak ayrı iş. Ürün, stok, kargo ve ödemenin tek panelden yönetilmesi gerekir.',
                'intro_en' => 'Setting up a store is easy; setting up a store that sells is another matter. Products, stock, shipping and payments have to live in one panel.',
                'needs' => [
                    'Sepetten ödemeye giden yolun kısa olması',
                    'Stok ve varyant (beden, renk) yönetimi',
                    'Kıbrıs\'a ve Türkiye\'ye ayrı kargo/teslimat kuralları',
                    'Mobilde tek elle tamamlanabilen kasa adımı',
                ],
                'needs_en' => [
                    'A short path from cart to payment',
                    'Stock and variant (size, colour) management',
                    'Separate shipping rules for Cyprus and Türkiye',
                    'A checkout that can be finished one-handed on mobile',
                ],
                'features' => [
                    'Sınırsız ürün, kategori ve varyant',
                    'Stok takibi ve tükenen ürün davranışı',
                    'Kupon, indirim ve kampanya kuralları',
                    'Sipariş yönetimi, durum bildirimleri, fatura bilgileri',
                    'Kargo bölgeleri ve ücret kuralları',
                    'Online ödeme entegrasyonu veya kapıda ödeme',
                ],
                'features_en' => [
                    'Unlimited products, categories and variants',
                    'Stock tracking and out-of-stock behaviour',
                    'Coupons, discounts and campaign rules',
                    'Order management, status notifications, invoice details',
                    'Shipping zones and pricing rules',
                    'Online payment integration or cash on delivery',
                ],
                'body' => '<p>E-ticarette kaybın çoğu kasada oluyor. Ziyaretçi ürünü beğeniyor, sepete atıyor ve ödeme adımında vazgeçiyor. Sebep genelde tasarım değil: zorunlu üyelik, uzun form, belirsiz kargo ücreti ya da mobilde yanlış çalışan bir alan.</p><h2>Kasa adımı kısa olmalı</h2><p>Üyeliksiz alışverişe izin veriyoruz, adres formunu asgari alana indiriyoruz ve kargo ücretini sepette — kasada değil — gösteriyoruz. Sürpriz kargo bedeli, sepeti terk etmenin en bilinen sebebi.</p><h2>Kıbrıs ve Türkiye aynı kurallarla çalışmıyor</h2><p>Teslimat bölgeleri, kargo süreleri ve ödeme yöntemleri iki pazarda farklı. Sistemi bölge bazlı kuruyoruz: hangi bölgeye hangi ücret, hangi ödeme yöntemi açık, bunu panelden siz belirliyorsunuz.</p><h3>Ödeme</h3><p>Online ödeme için sanal POS başvurusu ve banka onayı gerekiyor; bu süreç bizden bağımsız ilerliyor. Altyapıyı hazır kuruyoruz, onay gelene kadar kapıda ödeme ve havale ile satışa başlayabiliyorsunuz.</p><h3>Panelli mi, panelsiz mi</h3><p>Ürünü kendiniz eklemek istiyorsanız panel şart. Ürün sayısı çok az ve nadiren değişiyorsa panelsiz bir kurgu daha ucuz oluyor. Paketler sayfasında iki seçeneğin de fiyatı yazılı.</p>',
                'body_en' => '<p>In e-commerce most of the loss happens at checkout. The visitor likes the product, adds it to the cart, and abandons at payment. The cause is rarely design: forced registration, a long form, unclear shipping cost, or a field that misbehaves on mobile.</p><h2>Checkout must be short</h2><p>We allow guest checkout, reduce the address form to the minimum, and show shipping cost in the cart — not at the payment step. A surprise delivery charge is the best-known reason for abandonment.</p><h2>Cyprus and Türkiye do not run on the same rules</h2><p>Delivery zones, transit times and payment methods differ between the two markets. We build the system zone-based: which zone gets which rate, which payment methods are open — you set it from the panel.</p><h3>Payments</h3><p>Online payment requires a virtual POS application and bank approval, a process that runs independently of us. We build the infrastructure ready; until approval arrives you can start selling with cash on delivery and bank transfer.</p><h3>With or without a panel</h3><p>If you want to add products yourself, a panel is essential. If the catalogue is tiny and rarely changes, a panel-free build is cheaper. Both prices are published on the packages page.</p>',
                'seo_title' => 'E-Ticaret Sitesi Kurulumu | Stok, Kargo ve Ödeme Tek Panelde',
                'seo_title_en' => 'E-Commerce Store Setup | Stock, Shipping and Payments in One Panel',
                'seo_description' => 'Kıbrıs ve Türkiye\'ye satış yapan e-ticaret sitesi: sınırsız ürün, varyant, stok, kupon, kargo bölgeleri ve online ödeme. Fiyat açıkça yazılı.',
                'seo_description_en' => 'E-commerce stores selling into Cyprus and Türkiye: unlimited products, variants, stock, coupons, shipping zones and online payment.',
            ],

            [
                'slug' => 'saglik-ve-klinik',
                'name' => 'Sağlık & Klinik',
                'name_en' => 'Health & Clinics',
                'icon' => '🩺',
                'headline' => 'Klinik ve sağlık web sitesi',
                'headline_en' => 'Clinic and healthcare websites',
                'intro' => 'Hasta önce güven arıyor, sonra randevu. Site bu sırayı bozarsa çalışmıyor.',
                'intro_en' => 'Patients look for trust first and an appointment second. A site that reverses that order does not work.',
                'needs' => [
                    'Hekim ve uzmanlık bilgisi öne çıkmalı',
                    'Randevu talebi telefonu aramadan bırakılabilmeli',
                    'Sağlık turizmi hedefleniyorsa çok dilli yapı',
                    'Hasta verisi toplanıyorsa KVKK uyumu',
                ],
                'needs_en' => [
                    'Clinician credentials must be prominent',
                    'Appointment requests without having to call',
                    'A multilingual structure if you target health tourism',
                    'Data-protection compliance when collecting patient details',
                ],
                'features' => [
                    'Hekim profilleri: uzmanlık, eğitim, deneyim',
                    'Tedavi ve hizmet detay sayfaları',
                    'Randevu talep formu ve WhatsApp bağlantısı',
                    'Sık sorulanlar — hasta kaygılarını karşılayan bölüm',
                    'Klinik galerisi ve konum bilgisi',
                    'KVKK aydınlatma metni ve onay kutusu',
                ],
                'features_en' => [
                    'Clinician profiles: specialty, education, experience',
                    'Treatment and service detail pages',
                    'Appointment request form and WhatsApp link',
                    'An FAQ section that answers patient concerns',
                    'Clinic gallery and location',
                    'Privacy notice and consent checkbox',
                ],
                'body' => '<p>Sağlıkta karar duygusal ve temkinli veriliyor. Ziyaretçi fiyat karşılaştırmadan önce "bu kişi işini biliyor mu" sorusunu cevaplamak istiyor. Bu yüzden hekim profilleri, uzmanlık alanları ve tedavi anlatımları sitenin en önemli parçası.</p><h2>İçerik tıbbi iddia değil, bilgi olmalı</h2><p>Tedavi sayfalarını "işlem nedir, kimlere uygulanır, süreç nasıl işler, iyileşme ne kadar sürer" başlıklarıyla kuruyoruz. Sonuç garantisi veren ya da öncesi/sonrası vaadi taşıyan ifadelerden kaçınıyoruz — hem mevzuat açısından riskli, hem güven kırıcı.</p><h2>Randevu</h2><p>Çoğu klinikte tam otomatik takvim gerekmiyor; hastanın adı, telefonu, tercih ettiği gün ve şikâyetini bırakabildiği bir form yeterli oluyor. Talep size ulaştığında sekreter arıyor. Hasta hacmi büyükse takvimli sisteme geçilebiliyor.</p><h3>Sağlık turizmi</h3><p>Kıbrıs\'ta ve Antalya\'da yurt dışından hasta hedefleniyorsa İngilizce sürüm asgari şart. Bu durumda ulaşım, konaklama ve süreç takvimi gibi bilgiler de sayfaya giriyor — hasta yalnızca tedaviyi değil, seyahati planlıyor.</p><h3>KVKK</h3><p>Form üzerinden sağlık bilgisi toplanıyorsa aydınlatma metni ve açık rıza kutusu zorunlu. Bunu formun içine kuruyoruz; metnin hukuki içeriğini sizin danışmanınızın vermesi gerekiyor.</p>',
                'body_en' => '<p>Health decisions are made cautiously and emotionally. Before comparing prices, a visitor wants to answer one question: does this person know what they are doing? That is why clinician profiles, specialties and treatment explanations are the most important part of the site.</p><h2>Content should inform, not claim</h2><p>We structure treatment pages around what the procedure is, who it suits, how the process runs and how long recovery takes. We avoid outcome guarantees and before/after promises — legally risky and corrosive to trust.</p><h2>Appointments</h2><p>Most clinics do not need a full calendar system; a form capturing name, phone, preferred day and complaint is enough, with the front desk calling back. Calendar booking becomes worthwhile at higher volumes.</p><h3>Health tourism</h3><p>If you target patients from abroad, an English version is the minimum. Travel, accommodation and process timelines then belong on the page too — the patient is planning a trip, not just a treatment.</p><h3>Data protection</h3><p>If health information is collected through a form, a privacy notice and explicit consent checkbox are mandatory. We build them into the form; the legal wording has to come from your own adviser.</p>',
                'seo_title' => 'Klinik ve Sağlık Web Sitesi | Randevu Talebi Alan Yapı',
                'seo_title_en' => 'Clinic & Healthcare Websites | Built to Take Appointment Requests',
                'seo_description' => 'Klinik, muayenehane ve sağlık kuruluşları için hekim profilleri, tedavi sayfaları, randevu formu ve KVKK uyumlu veri toplama.',
                'seo_description_en' => 'Clinician profiles, treatment pages, appointment forms and compliant data collection for clinics and healthcare providers.',
            ],

            [
                'slug' => 'hukuk-muhasebe-danismanlik',
                'name' => 'Hukuk, Muhasebe & Danışmanlık',
                'name_en' => 'Law, Accounting & Consulting',
                'icon' => '⚖️',
                'headline' => 'Danışmanlık ve ofis web sitesi',
                'headline_en' => 'Professional services websites',
                'intro' => 'Bu işlerde site satış yapmaz, referans kontrolünü geçer. Karşı taraf sizinle çalışmadan önce bakar.',
                'intro_en' => 'Here the site does not sell; it passes a reference check. The other side looks before they engage.',
                'needs' => [
                    'Uzmanlık alanları net ve ayrı sayfalarda',
                    'Ekip, deneyim ve kurumsal bilgiler açık',
                    'Ciddiyeti bozmayan, sade ve hızlı tasarım',
                    'İhale ve teklif süreçlerinde referans verilebilir yapı',
                ],
                'needs_en' => [
                    'Practice areas stated clearly on separate pages',
                    'Team, experience and corporate details visible',
                    'Restrained, fast design that does not undercut seriousness',
                    'A structure you can cite in tenders and proposals',
                ],
                'features' => [
                    'Uzmanlık/hizmet alanı sayfaları',
                    'Ekip profilleri ve kurumsal bilgiler',
                    'Bilgi yazıları — mevzuat ve süreç açıklamaları',
                    'Yabancı dil seçeneği',
                    'Randevu/görüşme talep formu',
                    'Kariyer bölümü',
                ],
                'features_en' => [
                    'Practice-area pages',
                    'Team profiles and corporate information',
                    'Insight articles explaining regulation and process',
                    'Optional foreign language',
                    'Consultation request form',
                    'Careers section',
                ],
                'body' => '<p>Hukuk bürosu, muhasebe ofisi ya da danışmanlık firmasında müşteri genelde tavsiyeyle geliyor. Site yeni müşteri bulmuyor; tavsiye edilen kişinin arkasındaki firmayı doğruluyor. Bu yüzden ölçüt "ne kadar dikkat çekici" değil, "ne kadar güven verici".</p><h2>Uzmanlık alanları ayrı sayfa olmalı</h2><p>Tek bir "hizmetlerimiz" sayfasında maddeler hâlinde sıralamak yeterli değil. Her uzmanlık alanı kendi sayfasında anlatıldığında hem ziyaretçi aradığını buluyor, hem arama motorunda o konuda görünür oluyorsunuz.</p><h2>Bilgi yazıları işe yarıyor</h2><p>Mevzuat değişikliklerini ve süreçleri sade dille anlatan yazılar, bu sektörde en çok arama trafiği getiren içerik türü. Aynı zamanda yapay zekâ motorlarının alıntıladığı içerik de bu — soru soran birine cevap veren metinler.</p><h3>Ölçülü tasarım</h3><p>Animasyon ve efekt bu sektörde ters tepebiliyor. Sade tipografi, net hiyerarşi ve hızlı yüklenen sayfalar tercih ediyoruz.</p><h3>Kariyer</h3><p>Nitelikli personel rekabetinin yoğun olduğu bir alan. Açık pozisyonların ve başvuru formunun sitede olması, ilan sitelerine bağımlılığı azaltıyor.</p>',
                'body_en' => '<p>For a law firm, accountancy practice or consultancy, clients usually arrive by referral. The site does not find new clients; it verifies the firm behind the person who was recommended. So the measure is not how striking it is, but how much confidence it creates.</p><h2>Practice areas deserve their own pages</h2><p>Listing them as bullets on a single services page is not enough. When each area has its own page, visitors find what they came for and you become visible in search for that subject.</p><h2>Insight articles work</h2><p>Plain-language explanations of regulatory changes and processes bring the most search traffic in this sector. They are also the content generative engines quote most — text that answers a question.</p><h3>Restrained design</h3><p>Animation and effects can backfire here. We favour clean typography, clear hierarchy and pages that load fast.</p><h3>Careers</h3><p>Competition for qualified staff is intense. Publishing open roles and an application form on your own site reduces dependence on job boards.</p>',
                'seo_title' => 'Hukuk, Muhasebe ve Danışmanlık Web Sitesi | Kurumsal Yapı',
                'seo_title_en' => 'Law, Accounting & Consulting Websites | Corporate Structure',
                'seo_description' => 'Hukuk büroları, muhasebe ofisleri ve danışmanlık firmaları için uzmanlık alanı sayfaları, ekip profilleri, bilgi yazıları ve iki dilli yapı.',
                'seo_description_en' => 'Practice-area pages, team profiles, insight articles and bilingual structure for law firms, accountants and consultancies.',
            ],

            [
                'slug' => 'egitim-ve-kurs',
                'name' => 'Eğitim & Kurs',
                'name_en' => 'Education & Training',
                'icon' => '🎓',
                'headline' => 'Okul ve kurs web sitesi',
                'headline_en' => 'School and course websites',
                'intro' => 'Kayıt dönemi kısa. Site, veliyi ya da öğrenciyi bilgi aramaktan kayıt formuna en kısa yoldan götürmeli.',
                'intro_en' => 'Enrolment windows are short. The site has to move a parent or student from research to registration by the shortest route.',
                'needs' => [
                    'Program/kurs detayları: içerik, süre, ücret, kontenjan',
                    'Ön kayıt ve bilgi talep formu',
                    'Kayıt dönemi duyuruları ve takvim',
                    'Uluslararası öğrenci hedefleniyorsa İngilizce sürüm',
                ],
                'needs_en' => [
                    'Programme details: content, duration, fee, capacity',
                    'Pre-registration and enquiry forms',
                    'Enrolment announcements and calendar',
                    'An English version if you target international students',
                ],
                'features' => [
                    'Program ve kurs detay sayfaları',
                    'Ön kayıt formu, kontenjan durumu',
                    'Eğitmen profilleri',
                    'Duyuru ve takvim bölümü',
                    'Sık sorulanlar: ücret, ödeme, devam koşulları',
                    'Çok dilli içerik',
                ],
                'features_en' => [
                    'Programme and course detail pages',
                    'Pre-registration form and capacity status',
                    'Instructor profiles',
                    'Announcements and calendar',
                    'FAQ: fees, payment, attendance rules',
                    'Multilingual content',
                ],
                'body' => '<p>Eğitim kurumlarında trafik yıla yayılmıyor, kayıt dönemlerinde patlıyor. Sitenin o kısa pencerede net cevap vermesi gerekiyor: hangi program, ne kadar sürüyor, ne kadar tutuyor, nasıl başvurulur.</p><h2>Ücret bilgisi</h2><p>Ücreti gizlemek başvuruyu artırmıyor, aksine ciddiyetsizlik izlenimi bırakıyor. Net bir rakam veremiyorsanız aralık ya da "görüşmede netleşir" ifadesi bile boş bırakmaktan iyi çalışıyor.</p><h2>Ön kayıt</h2><p>Tam bir öğrenci bilgi sistemi kurmadan, ön kayıt formu çoğu kurum için yeterli: ad, iletişim, ilgilenilen program ve not alanı. Kontenjan takibi gerekiyorsa panelden yönetiliyor.</p><h3>Uluslararası öğrenci</h3><p>Kıbrıs\'ta üniversite çevresindeki kurslar ve dil okulları için İngilizce sürüm doğrudan pazar genişletiyor. Vize, konaklama ve ulaşım bilgileri de bu durumda sayfanın parçası oluyor.</p><h3>Duyuru düzeni</h3><p>Kayıt tarihleri, sınav takvimi ve tatil duyuruları panelden giriliyor; sitenin ana sayfasında güncel duyuru kendiliğinden öne çıkıyor.</p>',
                'body_en' => '<p>Traffic to education sites is not spread over the year; it spikes during enrolment. In that short window the site has to answer clearly: which programme, how long, how much, how to apply.</p><h2>Publishing fees</h2><p>Hiding the fee does not increase applications; it reads as evasive. If you cannot give a firm figure, a range or "confirmed at interview" still works better than leaving it blank.</p><h2>Pre-registration</h2><p>Without building a full student information system, a pre-registration form is enough for most institutions: name, contact, programme of interest and a notes field. Capacity tracking is handled from the panel when needed.</p><h3>International students</h3><p>For language schools and courses around universities in Cyprus, an English version directly widens the market. Visa, accommodation and travel information then belong on the page too.</p><h3>Announcements</h3><p>Enrolment dates, exam calendars and holiday notices are entered from the panel and surface automatically on the home page.</p>',
                'seo_title' => 'Okul ve Kurs Web Sitesi | Ön Kayıt Formu ve Program Sayfaları',
                'seo_title_en' => 'School & Course Websites | Pre-Registration and Programme Pages',
                'seo_description' => 'Okullar, kurslar ve dil merkezleri için program detay sayfaları, ön kayıt formu, kontenjan takibi, duyuru sistemi ve çok dilli yapı.',
                'seo_description_en' => 'Programme pages, pre-registration forms, capacity tracking, announcements and multilingual structure for schools and training centres.',
            ],

            [
                'slug' => 'sanayi-ve-bayi-agi',
                'name' => 'Sanayi & Bayi Ağı',
                'name_en' => 'Industry & Dealer Networks',
                'icon' => '🏭',
                'headline' => 'Sanayi ve B2B web sitesi',
                'headline_en' => 'Industrial and B2B websites',
                'intro' => 'Burada site son tüketiciye değil, satın alma birimine ve bayiye konuşuyor. Ürün kataloğu ve teknik doküman merkezde.',
                'intro_en' => 'Here the site talks to procurement teams and dealers, not end consumers. The product catalogue and technical documents sit at the centre.',
                'needs' => [
                    'Teknik özellikleriyle aranabilir ürün kataloğu',
                    'Katalog, teknik çizim ve sertifika indirme',
                    'Bayiye özel şifreli fiyat/stok alanı',
                    'İhracat hedefliyorsanız İngilizce sürüm',
                ],
                'needs_en' => [
                    'A searchable product catalogue with technical specs',
                    'Downloadable catalogues, drawings and certificates',
                    'A password-protected price/stock area for dealers',
                    'An English version if you export',
                ],
                'features' => [
                    'Ürün kataloğu: kategori, teknik özellik tablosu, kod',
                    'PDF katalog ve doküman arşivi',
                    'Teklif talep formu — ürün seçmeli',
                    'Bayi girişi: şifreli fiyat listesi ve sipariş formu',
                    'Sertifika ve kalite belgeleri bölümü',
                    'İngilizce sürüm ve ihracat bilgileri',
                ],
                'features_en' => [
                    'Product catalogue: categories, spec tables, part codes',
                    'PDF catalogue and document archive',
                    'Quote request form with product selection',
                    'Dealer login: protected price list and order form',
                    'Certificates and quality documents',
                    'English version and export information',
                ],
                'body' => '<p>Sanayi ve B2B tarafında siteye gelen kişi genelde bir satın alma sorumlusu ya da mühendis. Pazarlama diliyle değil, teknik veriyle ikna oluyor: ürün kodu, ölçü, malzeme, kapasite, sertifika.</p><h2>Katalog aranabilir olmalı</h2><p>PDF katalog indirtmek tek başına yetmiyor; ürünler sitede kendi sayfalarında olmadığında arama motorunda hiç görünmüyorsunuz. Ürünleri teknik özellik tablosuyla birlikte sayfa hâline getiriyor, PDF\'i de indirilebilir tutuyoruz.</p><h2>Bayi alanı</h2><p>Bayi fiyatı herkese açık olamaz. Şifreli bir alan kuruyoruz: bayi giriş yapıyor, kendi fiyat listesini ve stok durumunu görüyor, sipariş formunu dolduruyor. Bu, telefonla fiyat teyidi trafiğini belirgin şekilde azaltıyor.</p><h3>İhracat</h3><p>İngilizce sürüm, yurt dışı alıcının ilk durağı. Ürün adları ve teknik terimlerin doğru çevrilmesi burada tasarımdan daha önemli — yanlış terim, aramada hiç bulunmamak demek.</p><h3>Sertifikalar</h3><p>Kalite belgeleri, uygunluk sertifikaları ve test raporları ihale dosyalarında isteniyor. Bunları düzenli bir arşiv olarak yayınlamak, her talepte e-posta trafiği yaşamaktan daha verimli.</p>',
                'body_en' => '<p>On the industrial and B2B side, the person visiting is usually a buyer or an engineer. They are convinced by technical data, not marketing language: part code, dimensions, material, capacity, certification.</p><h2>The catalogue must be searchable</h2><p>Offering a PDF download is not enough; if products do not exist as pages, you are invisible in search. We turn products into pages with specification tables and keep the PDF downloadable alongside.</p><h2>The dealer area</h2><p>Dealer pricing cannot be public. We build a protected area: the dealer logs in, sees their own price list and stock, and submits an order form. This noticeably reduces phone traffic for price confirmations.</p><h3>Export</h3><p>The English version is the first stop for an overseas buyer. Correct translation of product names and technical terms matters more than design here — a wrong term means never being found.</p><h3>Certificates</h3><p>Quality certificates, conformity documents and test reports are requested in tender files. Publishing them as an organised archive beats handling each request by email.</p>',
                'seo_title' => 'Sanayi ve B2B Web Sitesi | Ürün Kataloğu ve Bayi Paneli',
                'seo_title_en' => 'Industrial & B2B Websites | Product Catalogue and Dealer Panel',
                'seo_description' => 'Üretici ve sanayi firmaları için teknik özellikli ürün kataloğu, doküman arşivi, teklif formu ve şifreli bayi fiyat/sipariş paneli.',
                'seo_description_en' => 'Technical product catalogues, document archives, quote forms and password-protected dealer pricing panels for manufacturers.',
            ],

            [
                'slug' => 'rent-a-car-ve-otomotiv',
                'name' => 'Rent a Car & Otomotiv',
                'name_en' => 'Car Rental & Automotive',
                'icon' => '🚗',
                'headline' => 'Araç kiralama ve galeri sitesi',
                'headline_en' => 'Car rental and dealership websites',
                'intro' => 'Müşteri tarihi giriyor, fiyatı görüyor, ayırtıyor. Bu üç adımı siteniz yapmıyorsa müşteri aracı komisyonlu platformdan kiralıyor.',
                'intro_en' => 'The customer picks dates, sees a price and reserves. If your site cannot do those three steps, they rent through a commission platform instead.',
                'needs' => [
                    'Tarih seçince müsait araçlar ve fiyat anında görünmeli',
                    'Sezona göre değişen fiyat tablosu elle güncellenebilmeli',
                    'Yabancı müşteri için çok dilli ve döviz gösterimi',
                    'Ehliyet, yaş ve depozito şartları baştan net olmalı',
                ],
                'needs_en' => [
                    'Picking dates must instantly show available cars and prices',
                    'Seasonal pricing you can update yourself',
                    'Multilingual and multi-currency for visitors from abroad',
                    'Licence, age and deposit conditions clear up front',
                ],
                'features' => [
                    'Araç filosu: segment, vites, yakıt, koltuk, bagaj',
                    'Tarih aralığına göre müsaitlik ve fiyat hesabı',
                    'Sezonluk fiyat tablosu ve minimum kiralama süresi',
                    'Rezervasyon talebi ya da online ödemeli kiralama',
                    'Teslim/iade noktaları (havalimanı, otel, ofis)',
                    'Galeri tarafı için: ikinci el ilan listesi ve filtre',
                ],
                'features_en' => [
                    'Fleet listing: segment, transmission, fuel, seats, luggage',
                    'Availability and pricing by date range',
                    'Seasonal rate table and minimum rental period',
                    'Booking request or online-paid rental',
                    'Pick-up and drop-off points (airport, hotel, office)',
                    'For dealerships: used-car listings with filters',
                ],
                'body' => '<p>Araç kiralamada rekabet fiyattan çok <strong>kolaylıktan</strong> gidiyor. Müşteri uçak biletini aldıktan sonra "Kıbrıs araç kiralama" diye arıyor ve ilk üç sitede tarih girip fiyat görebildiği yeri seçiyor. Fiyat için telefon açtırmak, o müşteriyi platforma göndermek demek.</p><h2>Fiyatı göstermek zorundasınız</h2><p>Sezona göre değişen bir fiyat tablosu kuruyoruz: dönem, araç grubu ve günlük ücret. Müşteri tarihi girdiğinde toplam tutarı görüyor. Fiyat değiştiğinde panelden siz güncelliyorsunuz, bizi beklemiyorsunuz.</p><h2>Şartları saklamayın</h2><p>Minimum yaş, ehliyet süresi, depozito ve yakıt politikası sayfada açıkça yazmalı. Bunları teslim anında öğrenen müşteri hem tartışma çıkarıyor hem kötü yorum bırakıyor. Açık yazmak rezervasyonu düşürmüyor, doğru müşteriyi getiriyor.</p><h3>Galeri tarafı</h3><p>İkinci el satışında ihtiyaç farklı: marka, model, yıl, kilometre ve fiyat aralığına göre filtrelenen bir ilan listesi. Satılan araç listede kalmalı ama "satıldı" işaretlenmeli — hem arşiv oluyor hem hareketliliği gösteriyor.</p><h3>Havalimanı trafiği</h3><p>Ercan ya da Larnaka teslim noktası olarak seçilebiliyorsa bunu ayrı bir sayfa hâline getirmek yerel aramada belirgin fark yaratıyor.</p>',
                'body_en' => '<p>In car rental the competition is less about price than <strong>convenience</strong>. After booking a flight, the customer searches for car hire and picks whichever of the first few sites lets them enter dates and see a price. Making them phone for a quote hands that customer to a platform.</p><h2>You have to show the price</h2><p>We build a seasonal rate table: period, vehicle group, daily rate. When the customer enters dates, they see a total. When rates change you update them from the panel without waiting for us.</p><h2>Do not hide the conditions</h2><p>Minimum age, licence tenure, deposit and fuel policy belong on the page. A customer who discovers them at handover argues and leaves a bad review. Stating them plainly does not reduce bookings; it brings the right ones.</p><h3>The dealership side</h3><p>Used-car sales need something different: listings filterable by make, model, year, mileage and price. Sold cars should stay listed but marked sold — it doubles as an archive and shows turnover.</p><h3>Airport traffic</h3><p>If you deliver to the airport, giving that its own page makes a marked difference in local search.</p>',
                'seo_title' => 'Rent a Car Web Sitesi | Tarih Seçmeli Müsaitlik ve Fiyat',
                'seo_title_en' => 'Car Rental Websites | Date-Based Availability and Pricing',
                'seo_description' => 'Araç kiralama ve galeri firmaları için tarih seçmeli müsaitlik, sezonluk fiyat tablosu, çok dilli yapı ve filtreli ikinci el ilan sistemi.',
                'seo_description_en' => 'Date-based availability, seasonal rate tables, multilingual structure and filterable used-car listings for rental firms and dealerships.',
            ],

            [
                'slug' => 'turizm-ve-tur-acentesi',
                'name' => 'Turizm & Tur Acentesi',
                'name_en' => 'Tourism & Tour Operators',
                'icon' => '🧭',
                'headline' => 'Tur ve transfer sitesi',
                'headline_en' => 'Tour and transfer websites',
                'intro' => 'Turu satan şey program değil, güven. Ziyaretçi neyi, kaç saatte, kaç paraya alacağını görmeden ayırtmıyor.',
                'intro_en' => 'What sells a tour is not the itinerary but trust. Nobody books until they can see what they get, how long it takes and what it costs.',
                'needs' => [
                    'Tur detayı: program, süre, dahil olan/olmayan, kalkış noktası',
                    'Tarihe göre müsaitlik ve kişi başı fiyat',
                    'Yabancı ziyaretçi için çok dilli ve döviz',
                    'Mobilde tek elle tamamlanabilen rezervasyon',
                ],
                'needs_en' => [
                    'Tour detail: itinerary, duration, what is included, departure point',
                    'Availability by date and per-person pricing',
                    'Multilingual and multi-currency for international visitors',
                    'A booking that can be finished one-handed on mobile',
                ],
                'features' => [
                    'Tur ve transfer detay sayfaları',
                    'Saatlik program (kalkış → duraklar → dönüş)',
                    'Dahil / dahil değil listesi',
                    'Tarih ve kişi sayısı seçmeli rezervasyon talebi',
                    'Galeri ve konum haritası',
                    'Çok dilli içerik, döviz gösterimi',
                ],
                'features_en' => [
                    'Tour and transfer detail pages',
                    'Hour-by-hour itinerary (departure → stops → return)',
                    'Included / not included lists',
                    'Booking request with date and party size',
                    'Gallery and location map',
                    'Multilingual content and currency display',
                ],
                'body' => '<p>Tur satışında ziyaretçi tanımadığı bir firmaya para yatırmayı düşünüyor. Bu yüzden sayfanın işi ikna etmek değil, <strong>belirsizliği kaldırmak</strong>: nereden kalkıyor, kaç saat sürüyor, öğle yemeği dahil mi, çocuk fiyatı var mı.</p><h2>Program saat saat yazılmalı</h2><p>"Bellapais ve Girne Kalesi turu" cümlesi hiçbir şey söylemiyor. Kalkış saati, duraklar, her durakta ne kadar kalındığı ve dönüş saati yazıldığında rezervasyon oranı belirgin şekilde değişiyor.</p><h2>Dahil olmayanı da yazın</h2><p>Müze giriş ücreti, içecek, bahşiş — dahil değilse açıkça belirtin. Turda öğrenen misafir memnuniyetsiz ayrılıyor ve bu değerlendirme sitelerine yansıyor.</p><h3>Çok dillilik pazarın kendisi</h3><p>Kıbrıs ve Antalya\'da tur alan kitlenin büyük kısmı Türkçe aramıyor. İngilizce asgari şart; pazarınıza göre Rusça, Almanca ya da İbranice eklemek doğrudan yeni müşteri demek.</p><h3>Transfer işi ayrı çalışıyor</h3><p>Havalimanı transferinde karar hızlı veriliyor: güzergâh, araç tipi, sabit fiyat. Bu sayfaların tur sayfalarından daha sade ve daha hızlı olması gerekiyor.</p>',
                'body_en' => '<p>Booking a tour means sending money to a company you do not know. So the page\'s job is not persuasion but <strong>removing uncertainty</strong>: where it departs, how long it runs, whether lunch is included, whether there is a child rate.</p><h2>Publish the itinerary by the hour</h2><p>"Bellapais and Kyrenia Castle tour" tells the visitor nothing. Departure time, stops, time at each stop and return time change booking rates noticeably.</p><h2>List what is not included</h2><p>Museum entry, drinks, tips — if they are extra, say so. A guest who finds out mid-tour leaves unhappy, and that lands on review sites.</p><h3>Multilingual is the market itself</h3><p>Most people booking tours in Cyprus and Antalya are not searching in Turkish. English is the minimum; Russian, German or Hebrew can each open a new audience.</p><h3>Transfers work differently</h3><p>Airport transfers are decided fast: route, vehicle type, fixed price. Those pages need to be simpler and faster than tour pages.</p>',
                'seo_title' => 'Tur ve Transfer Web Sitesi | Rezervasyon Alan Çok Dilli Yapı',
                'seo_title_en' => 'Tour & Transfer Websites | Multilingual Booking',
                'seo_description' => 'Tur acenteleri ve transfer firmaları için saatlik program, tarih seçmeli rezervasyon, çok dilli içerik ve döviz gösterimi.',
                'seo_description_en' => 'Hour-by-hour itineraries, date-based booking, multilingual content and currency display for tour operators and transfer companies.',
            ],

            [
                'slug' => 'guzellik-ve-bakim',
                'name' => 'Güzellik & Bakım',
                'name_en' => 'Beauty & Wellness',
                'icon' => '💇',
                'headline' => 'Kuaför ve güzellik salonu sitesi',
                'headline_en' => 'Salon and beauty websites',
                'intro' => 'Bu işte müşteri Instagram\'dan bakıp randevu alıyor. Sitenin görevi işi göstermek ve randevuyu kolaylaştırmak.',
                'intro_en' => 'Here the customer looks at Instagram and books. The site\'s job is to show the work and make booking easy.',
                'needs' => [
                    'Hizmet listesi süre ve fiyatıyla birlikte',
                    'Randevu talebi WhatsApp\'a ya da forma tek dokunuş',
                    'Yapılan işlerin göründüğü hızlı yüklenen galeri',
                    'Google Haritalar ve çalışma saatleri her zaman doğru',
                ],
                'needs_en' => [
                    'A service list with duration and price',
                    'One tap from booking to WhatsApp or a form',
                    'A fast-loading gallery that shows real work',
                    'Google Maps and opening hours always accurate',
                ],
                'features' => [
                    'Panelden yönetilen hizmet menüsü: süre, fiyat, açıklama',
                    'Randevu talep formu (tarih, saat aralığı, hizmet)',
                    'Önce/sonra ve iş galerisi',
                    'Ekip profilleri — müşteri kişiye geliyor',
                    'Instagram bağlantısı ve WhatsApp düğmesi',
                    'Kampanya / paket duyuru alanı',
                ],
                'features_en' => [
                    'Panel-managed service menu: duration, price, description',
                    'Booking request form (date, time window, service)',
                    'Before/after and work gallery',
                    'Team profiles — clients come for a person',
                    'Instagram link and WhatsApp button',
                    'Promotions and package announcements',
                ],
                'body' => '<p>Güzellik ve bakım sektöründe sitenin rolü sıkça yanlış anlaşılıyor: "Instagram\'ımız var, siteye gerek yok" deniyor. Ama Instagram\'da fiyat yazmıyor, hizmet süresi yazmıyor ve Google\'da aranmıyorsunuz. Site bu üç boşluğu dolduruyor.</p><h2>Fiyatı yazın</h2><p>Bu sektörde en çok tereddüt fiyattan doğuyor. Hizmet menüsünü süre ve fiyatla birlikte yayınlamak, "ne kadar" sorusuyla gelen mesaj trafiğini azaltıyor ve gelen müşteriyi hazır getiriyor. Fiyat aralığı vermek bile tamamen boş bırakmaktan iyi çalışıyor.</p><h2>Müşteri kişiye geliyor</h2><p>Kuaförde ve güzellik salonunda bağlılık salona değil, uzmanın kendisine. Ekip profilleri koymak randevu oranını artırıyor; müşteri kimden hizmet alacağını bilerek geliyor.</p><h3>Galeri hızlı olmalı</h3><p>Yüzlerce fotoğraf koymak siteyi öldürüyor. Görselleri modern formatta sıkıştırıp tembel yüklüyoruz; ziyaretçi kaydırdıkça iniyor.</p><h3>Yerel arama</h3><p>"Yakınımdaki kuaför" aramalarında Google Business Profile belirleyici. Sitedeki adres, telefon ve çalışma saati o kayıtla birebir aynı tutulmalı — tutarsızlık sıralamayı düşürüyor.</p>',
                'body_en' => '<p>In beauty and wellness the role of a site is often misjudged: "we have Instagram, we do not need one." But Instagram does not list prices or durations, and you are not found on Google there. The site fills those three gaps.</p><h2>Publish your prices</h2><p>Most hesitation in this sector comes from price. A service menu with duration and price cuts the "how much is it" message traffic and brings customers in already informed. Even a range beats leaving it blank.</p><h2>Clients come for a person</h2><p>Loyalty in salons attaches to the stylist, not the salon. Team profiles raise booking rates because the client knows who they are seeing.</p><h3>The gallery has to be fast</h3><p>Hundreds of photos kill a site. We compress into modern formats and load lazily as the visitor scrolls.</p><h3>Local search</h3><p>Google Business Profile decides "salon near me". The address, phone and hours on the site must match that listing exactly — inconsistency lowers ranking.</p>',
                'seo_title' => 'Kuaför ve Güzellik Salonu Web Sitesi | Randevu ve Hizmet Menüsü',
                'seo_title_en' => 'Salon & Beauty Websites | Booking and Service Menus',
                'seo_description' => 'Kuaför, güzellik salonu ve bakım merkezleri için süre-fiyatlı hizmet menüsü, randevu formu, iş galerisi ve WhatsApp bağlantısı.',
                'seo_description_en' => 'Service menus with duration and price, booking forms, work galleries and WhatsApp links for salons and beauty studios.',
            ],

            [
                'slug' => 'etkinlik-ve-organizasyon',
                'name' => 'Etkinlik & Organizasyon',
                'name_en' => 'Events & Weddings',
                'icon' => '🎉',
                'headline' => 'Düğün ve organizasyon sitesi',
                'headline_en' => 'Wedding and event venue websites',
                'intro' => 'Tek bir işin bütçesi yüksek, karar süreci uzun. Site burada mekânı gezdiren ve tarih müsaitliğini gösteren bir satış aracı.',
                'intro_en' => 'High value per booking, long decision cycle. The site here is a sales tool that walks people through the venue and shows date availability.',
                'needs' => [
                    'Mekânı gerçekten gösteren, düzenli bir galeri',
                    'Tarih müsaitliği — en çok sorulan soru bu',
                    'Kapasite, paket kapsamı ve fiyat aralığı',
                    'Yurt dışından gelen çiftler için İngilizce sürüm',
                ],
                'needs_en' => [
                    'A well-organised gallery that genuinely shows the venue',
                    'Date availability — the single most asked question',
                    'Capacity, package scope and price range',
                    'An English version for couples travelling in',
                ],
                'features' => [
                    'Mekân galerisi: alan alan, gündüz/gece',
                    'Kapasite ve oturma düzeni bilgisi',
                    'Paket karşılaştırma (dahil olan hizmetler)',
                    'Tarih sorgulu teklif talep formu',
                    'Gerçekleşen organizasyon arşivi',
                    'Konum, ulaşım ve konaklama bilgisi',
                ],
                'features_en' => [
                    'Venue gallery by space, day and night',
                    'Capacity and seating layouts',
                    'Package comparison with included services',
                    'Enquiry form with a date field',
                    'Archive of past events',
                    'Location, transport and accommodation info',
                ],
                'body' => '<p>Düğün ve organizasyon işinde ziyaretçi aylar önce araştırmaya başlıyor, onlarca mekân karşılaştırıyor ve genelde tek bir soruyla iletişime geçiyor: "15 Haziran boş mu?"</p><h2>Tarih sorusunu forma taşıyın</h2><p>Teklif formuna tarih alanı koymak, gelen taleplerin kalitesini değiştiriyor. Siz de "hangi tarih" diye yazışmadan doğrudan cevap veriyorsunuz.</p><h2>Galeri düzenli olmalı</h2><p>Yüz fotoğrafı alt alta dizmek işe yaramıyor. Mekânı alanlara ayırıyoruz — bahçe, salon, teras — ve her alanı gündüz/gece gösteriyoruz. Çift kafasında mekânı kurabilmeli.</p><h2>Fiyat aralığı verin</h2><p>Kesin fiyat vermek mümkün olmayabilir; kişi başı aralık ya da "şu bütçeden başlıyor" ifadesi bile bütçesi uymayan talepleri eliyor ve zamanınızı koruyor.</p><h3>Kıbrıs\'ta destinasyon düğünü</h3><p>Yurt dışından gelen çiftler için mekân kadar konaklama, ulaşım ve resmi işlemler de merak konusu. Bu bilgileri sayfaya koymak, rakiplerin çoğunun atladığı bir fark yaratıyor.</p>',
                'body_en' => '<p>Couples start researching months ahead, compare dozens of venues, and usually make contact with a single question: "is 15 June free?"</p><h2>Move the date question into the form</h2><p>Adding a date field to the enquiry form changes the quality of what arrives. You answer directly instead of exchanging messages to establish the date.</p><h2>The gallery must be organised</h2><p>Stacking a hundred photos does not work. We split the venue into spaces — garden, hall, terrace — and show each by day and night, so the couple can picture the event.</p><h2>Give a price range</h2><p>An exact figure may be impossible, but a per-head range or "starting from" filters out enquiries that were never going to fit and protects your time.</p><h3>Destination weddings in Cyprus</h3><p>Couples travelling in care about accommodation, transport and paperwork as much as the venue. Putting that on the page is a difference most competitors skip.</p>',
                'seo_title' => 'Düğün ve Organizasyon Web Sitesi | Tarih Sorgulu Teklif Formu',
                'seo_title_en' => 'Wedding & Event Venue Websites | Date-Aware Enquiry Forms',
                'seo_description' => 'Düğün mekânları ve organizasyon firmaları için alan alan galeri, kapasite bilgisi, paket karşılaştırma ve tarih sorgulu teklif formu.',
                'seo_description_en' => 'Space-by-space galleries, capacity details, package comparison and date-aware enquiry forms for venues and event companies.',
            ],

            [
                'slug' => 'spor-ve-fitness',
                'name' => 'Spor & Fitness',
                'name_en' => 'Sports & Fitness',
                'icon' => '🏋️',
                'headline' => 'Spor salonu ve stüdyo sitesi',
                'headline_en' => 'Gym and studio websites',
                'intro' => 'Kararı geciktiren iki şey var: fiyat ve "bana uygun mu" sorusu. Site ikisini de ilk ekranda cevaplamalı.',
                'intro_en' => 'Two things delay the decision: price, and "is this for me?". The site should answer both above the fold.',
                'needs' => [
                    'Üyelik paketleri ve fiyatları açıkça yazılı',
                    'Ders programı — hangi gün, hangi saat, kim',
                    'Deneme dersi / ücretsiz gün talep formu',
                    'Salonu ve ekipmanı gösteren gerçek fotoğraflar',
                ],
                'needs_en' => [
                    'Membership packages and prices stated openly',
                    'A class timetable — day, time, instructor',
                    'A trial session request form',
                    'Real photos of the space and equipment',
                ],
                'features' => [
                    'Üyelik paketleri ve fiyat tablosu',
                    'Haftalık ders programı (panelden güncellenir)',
                    'Eğitmen profilleri ve uzmanlık alanları',
                    'Deneme dersi talep formu',
                    'Salon galerisi',
                    'Sık sorulanlar: dondurma, iptal, yaş sınırı',
                ],
                'features_en' => [
                    'Membership packages and pricing table',
                    'Weekly class timetable, managed from the panel',
                    'Instructor profiles and specialisms',
                    'Trial session request form',
                    'Facility gallery',
                    'FAQ: freezing, cancellation, age limits',
                ],
                'body' => '<p>Spor salonu arayan kişi genelde kararsız: başlamak istiyor ama erteliyor. Sitenin işi bu kişiyi ikna etmek değil, <strong>bahaneleri kaldırmak</strong>.</p><h2>Fiyatı gizlemeyin</h2><p>Bu sektörde "fiyat için arayın" yaklaşımı yaygın ama ters tepiyor. Ziyaretçi aramıyor, fiyatını yazan salona gidiyor. Paketleri ve aylık tutarları yayınlamak en hızlı iyileştirme.</p><h2>Program sitede olmalı</h2><p>Ders saatlerini Instagram hikâyesinde paylaşmak işe yaramıyor; ertesi gün kayboluyor. Haftalık programı panelden güncellenen bir tablo hâline getiriyoruz — hem üye bakıyor hem arama motoru okuyor.</p><h3>Deneme dersi</h3><p>Üyelik satmadan önce kapıdan içeri sokmak gerekiyor. Sitede tek adımlık bir deneme talebi formu, en yüksek dönüşümlü unsur oluyor.</p><h3>Şartları yazın</h3><p>Üyelik dondurma, iptal ve devir koşulları sonradan tartışma çıkaran konular. Sıkça sorulanlar bölümünde açıkça yazmak hem güven veriyor hem sizi koruyor.</p>',
                'body_en' => '<p>Someone looking for a gym is usually undecided — they want to start but keep postponing. The site\'s job is not to persuade them but to <strong>remove the excuses</strong>.</p><h2>Do not hide the price</h2><p>"Call for pricing" is common here and it backfires. Visitors do not call; they go to the gym that publishes its rates. Listing packages and monthly fees is the single fastest improvement.</p><h2>Put the timetable on the site</h2><p>Sharing class times in an Instagram story does not work; it disappears the next day. We build a weekly timetable you update from the panel — members read it and so do search engines.</p><h3>Trial sessions</h3><p>You have to get people through the door before selling a membership. A one-step trial request form is usually the highest-converting element on the site.</p><h3>Publish the terms</h3><p>Freezing, cancellation and transfer rules cause arguments later. Stating them in the FAQ builds trust and protects you.</p>',
                'seo_title' => 'Spor Salonu Web Sitesi | Üyelik Paketleri ve Ders Programı',
                'seo_title_en' => 'Gym & Studio Websites | Memberships and Class Timetables',
                'seo_description' => 'Spor salonu, pilates ve dövüş sporları stüdyoları için üyelik paketleri, haftalık ders programı, eğitmen profilleri ve deneme dersi formu.',
                'seo_description_en' => 'Membership packages, weekly timetables, instructor profiles and trial request forms for gyms and studios.',
            ],

            [
                'slug' => 'lojistik-ve-nakliyat',
                'name' => 'Lojistik & Nakliyat',
                'name_en' => 'Logistics & Freight',
                'icon' => '🚚',
                'headline' => 'Nakliyat ve lojistik sitesi',
                'headline_en' => 'Logistics and freight websites',
                'intro' => 'Müşteri iki şey soruyor: bu güzergâha bakıyor musunuz, ne kadar tutar. Site bu ikisini cevaplayamıyorsa telefon çalmıyor.',
                'intro_en' => 'Customers ask two things: do you cover this route, and what does it cost. If the site cannot answer, the phone does not ring.',
                'needs' => [
                    'Hizmet verilen güzergâhlar ve taşıma tipleri net olmalı',
                    'Teklif formu yükü tarif ettirmeli (hacim, ağırlık, tarih)',
                    'Kurumsal müşteri için referans ve belge güveni',
                    'Gönderi takibi sorulacaksa nereden bakılacağı belli olmalı',
                ],
                'needs_en' => [
                    'Clear routes covered and transport types',
                    'A quote form that captures the load (volume, weight, date)',
                    'Credibility documents for corporate clients',
                    'A clear place to track a shipment if you offer it',
                ],
                'features' => [
                    'Hizmet sayfaları: karayolu, deniz, hava, depolama',
                    'Güzergâh listesi (KKTC–Türkiye–Avrupa)',
                    'Detaylı teklif formu: yük tipi, ölçü, tarih, adresler',
                    'Evden eve nakliyat için ayrı akış',
                    'Belgeler ve yetki sertifikaları bölümü',
                    'Takip bağlantısı veya takip formu',
                ],
                'features_en' => [
                    'Service pages: road, sea, air, warehousing',
                    'Route list (North Cyprus – Türkiye – Europe)',
                    'Detailed quote form: cargo type, dimensions, date, addresses',
                    'A separate flow for household moves',
                    'Certificates and licences section',
                    'Tracking link or tracking form',
                ],
                'body' => '<p>Nakliyat ve lojistikte gelen talebin kalitesi her şeyi belirliyor. "Fiyat alabilir miyim" diye gelen bir e-posta, karşılıklı beş mesaj demek. Teklif formunu doğru kurmak bu trafiği tek adıma indiriyor.</p><h2>Teklif formu yükü tarif ettirmeli</h2><p>Yük tipi, yaklaşık hacim/ağırlık, çıkış ve varış adresi, istenen tarih. Bu dört alan dolduğunda siz fiyat verebilecek durumda oluyorsunuz. Genel bir "mesajınız" kutusu bunu yapmıyor.</p><h2>Güzergâhı yazın</h2><p>Hangi ülkeler, hangi limanlar, hangi taşıma tipleri — bunlar hem müşterinin ilk sorusu hem de arama motorunun okuduğu içerik. "Kıbrıs Türkiye nakliyat" gibi aramalarda görünmenin yolu bu sayfalardan geçiyor.</p><h3>Kurumsal müşteri belge arıyor</h3><p>Yetki belgeleri, sigorta ve sertifikalar ihale ve tedarikçi onay süreçlerinde isteniyor. Bunları düzenli bir bölümde yayınlamak her talepte e-posta trafiğinden kurtarıyor.</p><h3>Evden eve ayrı bir iş</h3><p>Bireysel taşınma müşterisi farklı şey soruyor: paketleme dahil mi, asansör var mı, sigortalı mı. Bu akışı kurumsal taşımacılıktan ayırmak ikisinin de dönüşümünü artırıyor.</p>',
                'body_en' => '<p>In freight, the quality of the incoming enquiry decides everything. An email saying "can I get a price" means five messages back and forth. A well-built quote form collapses that into one step.</p><h2>Make the form describe the load</h2><p>Cargo type, approximate volume or weight, origin and destination, requested date. With those four fields filled you can actually quote. A generic "your message" box cannot.</p><h2>Publish your routes</h2><p>Which countries, which ports, which transport modes — that is both the customer\'s first question and the content search engines read.</p><h3>Corporate clients want documents</h3><p>Licences, insurance and certificates get requested during tenders and supplier approval. Publishing them in one organised section saves the email traffic.</p><h3>Household moves are a different business</h3><p>Private movers ask different things: is packing included, is there a lift, is it insured. Separating that flow from corporate freight improves both.</p>',
                'seo_title' => 'Nakliyat ve Lojistik Web Sitesi | Detaylı Teklif Formu',
                'seo_title_en' => 'Logistics & Freight Websites | Structured Quote Forms',
                'seo_description' => 'Nakliyat ve lojistik firmaları için güzergâh sayfaları, yük tarif ettiren teklif formu, belge arşivi ve evden eve taşımacılık akışı.',
                'seo_description_en' => 'Route pages, load-describing quote forms, document archives and household-move flows for logistics companies.',
            ],

            [
                'slug' => 'dernek-vakif-ve-kamu',
                'name' => 'Dernek, Vakıf & Kamu',
                'name_en' => 'Nonprofits & Public Sector',
                'icon' => '🤝',
                'headline' => 'Dernek ve vakıf sitesi',
                'headline_en' => 'Nonprofit and public sector websites',
                'intro' => 'Burada satılan şey ürün değil güven. Şeffaflık, sitenin süsü değil ana işlevi.',
                'intro_en' => 'What is being sold here is trust, not a product. Transparency is the site\'s main function, not decoration.',
                'needs' => [
                    'Ne yaptığınız somut ve ölçülebilir anlatılmalı',
                    'Bağış yapan paranın nereye gittiğini görmeli',
                    'Duyuru ve etkinlik takvimi güncel kalmalı',
                    'Üyelik / gönüllülük başvurusu kolay olmalı',
                ],
                'needs_en' => [
                    'Concrete, measurable explanation of what you do',
                    'Donors must see where the money goes',
                    'Announcements and an events calendar kept current',
                    'Easy membership and volunteer applications',
                ],
                'features' => [
                    'Projeler ve faaliyet sayfaları',
                    'Faaliyet raporu / mali tablo arşivi',
                    'Bağış bilgileri (banka, IBAN, online ödeme)',
                    'Üyelik ve gönüllü başvuru formu',
                    'Duyuru ve etkinlik takvimi',
                    'Yönetim kurulu ve tüzük bilgileri',
                ],
                'features_en' => [
                    'Project and activity pages',
                    'Annual report and financial statement archive',
                    'Donation details (bank, IBAN, online payment)',
                    'Membership and volunteer application forms',
                    'Announcements and events calendar',
                    'Board members and governing documents',
                ],
                'body' => '<p>Dernek ve vakıf sitelerinde en sık görülen hata, sayfayı duygusal metinle doldurup somut bilgi vermemek. Bağış yapacak kişi duygulanmak için değil, <strong>güvenmek</strong> için geliyor.</p><h2>Rakam verin</h2><p>"Çocuklara destek oluyoruz" cümlesi ile "geçen yıl 340 öğrenciye kırtasiye desteği verdik" cümlesi arasında bağış açısından büyük fark var. Projeleri sayıyla anlatmak en etkili değişiklik.</p><h2>Mali şeffaflık</h2><p>Faaliyet raporlarını ve mali tabloları indirilebilir biçimde yayınlamak, kurumsal bağışçı ve fon başvurularında doğrudan aranan bir şey. Düzenli bir arşiv bölümü kuruyoruz.</p><h3>Bağış akışı</h3><p>Banka ve IBAN bilgisi asgari şart; online ödeme isteniyorsa sanal POS başvurusu gerekiyor ve bu süreç kurumdan kuruma değişiyor. Altyapıyı hazır kuruyoruz, onay gelene kadar havale ile devam ediliyor.</p><h3>Duyuru düzeni</h3><p>Genel kurul, etkinlik ve burs başvuru tarihleri panelden giriliyor, ana sayfada güncel duyuru kendiliğinden öne çıkıyor. Güncelliğini yitirmiş bir dernek sitesi, faal olmadığı izlenimi veriyor.</p>',
                'body_en' => '<p>The most common mistake on nonprofit sites is filling the page with emotive copy and no concrete information. A donor arrives wanting to <strong>trust</strong> you, not to be moved.</p><h2>Use numbers</h2><p>"We support children" and "last year we provided school supplies to 340 students" are very different sentences for a donor. Describing projects with figures is the most effective change you can make.</p><h2>Financial transparency</h2><p>Publishing downloadable annual reports and financial statements is directly requested by corporate donors and grant programmes. We build an organised archive for them.</p><h3>Donations</h3><p>Bank and IBAN details are the minimum; online payment needs a virtual POS application, which varies by organisation. We build the infrastructure ready and you continue by transfer until approval.</p><h3>Announcements</h3><p>General assemblies, events and scholarship deadlines are entered from the panel and surface automatically. An out-of-date nonprofit site reads as an inactive organisation.</p>',
                'seo_title' => 'Dernek ve Vakıf Web Sitesi | Şeffaflık, Bağış ve Üyelik',
                'seo_title_en' => 'Nonprofit Websites | Transparency, Donations and Membership',
                'seo_description' => 'Dernek, vakıf ve kamu kurumları için proje sayfaları, faaliyet raporu arşivi, bağış bilgileri, üyelik formu ve duyuru takvimi.',
                'seo_description_en' => 'Project pages, report archives, donation details, membership forms and event calendars for nonprofits and public bodies.',
            ],
        ];
    }
}
